### ISSUE TITLE
Kinky consumption function behaves weird when Rboro=Rsave

### ISSUE THREAD

**Issue by pavelsolis** [econ-ark/HARK#100]
The solution to the kinky consumer behaves weird when Rboro=Rsave. For example, in ‘ConsumerParameters.py’ set both rates equal to 1.02, then run ‘ConsIndShockModel.py’ and look at the (kinky) consumption function plotted.
The code can send a message indicating that for that case it is better to use the model without kinks.
One possible fix could be to introduce in the current line 1414 of ConsIndShockModel.py the following:
assert Rboro>Rsave, 'Interest factor on debt is equal to interest factor on savings, \
                         the model without kinks is best suited for that case.'

**Comment by mnwhite** [comment]
You are correct.  Here's what's happening-- or at least the beginning of what sets off a chain reaction of wrong.

In line 1321, we add *two* copies of aNrm = 0.0 into the grid aNrmNow; in lines 1335-6, we assign Rboro as the relevant interest factor for all of the aNrmNow values up to the first zero, and Rsave for the values starting at the second zero.  When Rboro == Rsave, we end up with two identical (mNrm,cNrm) interpolation points, which means that the grid of x values for the interpolator is not *strictly* increasing.  This causes the interpolation routine to fail, and thus nonsense to come out.

The fix for this is to simply put conditionals on lines 1321 and 1336: if Rboro > Rsave (with a one line else portion for the former).  This effectively skips the extra work for KinkedR and acts just like IndShock, other than recalculating MPCmin and hNrmNow around line 1346, which just duplicates earlier work.

I'll merge in this fix momentarily, rather than the "assert Rboro > Rsave" version you PR'ed.  Thank you for bringing this to our attention!
