### ISSUE TITLE
Allow time-varying UnempPrb

### ISSUE THREAD

**Issue by Mv77** [econ-ark/HARK#1015]
`construct_lognormal_income_process_unemployment` in `ConsIndShockModel.py` currently only accepts constant unemployment probabilities which can be different while working and while retired, `UnempPrb` and `UnempPrbRet`.

This setup does not allow one to implement, for instance:
- _Age-specific unemployment probabilities while working_ (I think it is the case that unemployment is much higher for young people, at least in my native Colombia).
- _Age-varying but risk-free retirement income_: most papers assume that retirement income is constant, but there are exceptions. Cagetti (2003), for instance, has a downward trend in retirement income that is still safe. A way to achieve this in HARK is to ignore the built-in retirement functionality, choose the appropriate `PermGroFac` sequence and make `PermShkStd = TranShkStd = 0` after some age. The issue is that one can not shut down unemployment after some age.

Thus, I think a time-varying `UnempPrb` would be a nice feature to have.

**Comment by sbenthall** [comment]
I completely agree. I was just running into a related issue with the `Adjust` shocks.

I think that rather than having the age-varying nature of these variables be hard coded into the models, it should be pulled out into an age-varying distribution class. I have ticketed this in #1017 

I'm not 100% sure that the 'age-varying' use case is the same as the 'time-varying' one here. Can you confirm? It seems that sometimes this time-varying functionality is being handled in separate ways by the simulation and solution code, though it's really a model element.

**Comment by Mv77** [comment]
Hey,

Yes, I do think they are the same use case. I usually interpret the models annually but what I meant was an unemployment probability that can change from period to period (whatever a time period represents).

A time-varying distribution class might be useful for finite-horizon models. A suggestion if you do implement it is for it to have the capacity to produce the time-specific distributions easily, so that they can still be passed to the solvers without passing the whole age-varying distributions.

**Comment by Mv77** [comment]
I do agree that these case-handling bits of code where one might run through agents checking their `t_cycle` and drawing from different distributions is repeated throughout HARK, so a tool to deal with it would be nice.

**Comment by sbenthall** [comment]
Perfect. Let me see if I can get a good PR for this by Thursday.

**Comment by sbenthall** [comment]
Now that #1018 is in, this might be easier.

**Comment by mnwhite** [comment]
I think HARK already handles this.
