### ISSUE TITLE
cstwMPC crashes

### ISSUE THREAD

**Issue by llorracc-git** [econ-ark/HARK#109]
Downloading and running the current version of HARK generates the error below.

~~~

ccarroll:tmp ccarroll$ cd HARK-master
ccarroll:HARK-master ccarroll$ cd cstwMPC
ccarroll:cstwMPC ccarroll$ python cstwMPC.py
divide by zero encountered in log
Traceback (most recent call last):
  File "cstwMPC.py", line 628, in <module>
    InfiniteType = cstwMPCagent(**Params.init_infinite)
  File "cstwMPC.py", line 63, in __init__
    self.update()
  File "cstwMPC.py", line 114, in update
    self.makeIncShkHist()
AttributeError: cstwMPCagent instance has no attribute 'makeIncShkHist'
~~~

**Comment by derinaksit** [comment]
I compared the 6-month old and 3-month old versions of the cstwMPC codes. Apparently, makeIncShkHist definition is deleted under the IndShockConsumerType class in ConsIndShockModel.py, a class which is imported by cstwMPC. 

After putting the makeIncShkHist definition back within IndShockConsumerType, the code gives another error, "AttributeError: cstwMPCagent instance has no attribute 'AgentCount'". I think this is because there are some additions to the HARKcore.py such as the definition initializeSim(self).

**Comment by mnwhite** [comment]
cstwMPC.py is antiquated and has been superceded by cstwMPCnew.py.  The former should probably be deleted, but I believe there is a small bit of functionality still in cstwMPC that isn't in the new version.

The new version was created after the simulation overhaul, which changed quite a bit.

**Comment by llorracc-git** [comment]
Thanks.  But let me advocate that we never leave as the "base" version in the public archive, a version that does not work.  We can always revert to the last version that did work, before working on a new version.  

(Am writing this from class, where I'm trying to teach python, github, Jupyter simultaneously)

**Comment by mnwhite** [comment]
Of course, it turns out the cstwMPCnew.py *also* does not work in its most simple specification (the no aggregate shocks model).  The fix is 3 lines long, and I'll add it after David deals with my PRs from January.

**Comment by dclow** [comment]
Well-deserved burn.  It's on my calendar for tomorrow!

**Comment by mnwhite** [comment]
Closing this issue because cstwMPCnew has been renamed to cstwMPC (and the old version is now labeled old).
