### ISSUE TITLE
Passing arguments to Solvers 

### ISSUE THREAD

**Issue by alanlujan91** [econ-ark/HARK#1103]
When initializing an `AgentType`, we usually pass a dictionary of parameters. 

When initializing a `Solver`, we pass a long list of parameters 1 by 1. 

https://github.com/econ-ark/HARK/blob/f338c976c813991a095a0d3fea9967232ea59e07/HARK/ConsumptionSaving/ConsPortfolioModel.py#L476-L495

Is there a way to pass a container (dictionary or other pyobject) of parameters instead? Would this be desirable?

**Comment by alanlujan91** [comment]
I'm imagining something like 

```   
   def __init__(self, solution_next, params):
```

**Comment by mnwhite** [comment]
The code could be restructured this way, yes. The very first method a
Solver calls (probably as part of its __init__) would be to store the
parameters from the dictionary that it was expecting to receive (named in a
list of keys for the Solver subclass). This could make it easier to extend
Solver subclasses to further models, as we don't need to deal with
"vestigial inputs".

HARK's `solve` code is currently structured to pull the list of variable
names from the solveOnePeriod function (actually looking at the names of
its inputs), and then construct the parameter dictionary to be passed to it
by pulling from the corresponding attributes of `self`. It would take a
bunch of restructuring, but it could be written so that the dictionary
itself is passed as the argument, rather than "unpacked" with
`**parameter_dict`.

**Comment by sbenthall** [comment]
Yes -- I believe an unpacked parameters dict should work with the code as-in, if you are writing a new solver that creates Solver objects.

https://docs.python.org/2/tutorial/controlflow.html#unpacking-argument-lists

Maybe related to the possibility of using dataclasses for Solution objects: #605

Note that for AgentType, the specific handling of the parameters dictionary as meaning a set of _model parameters_ is supported by the Model class.

https://github.com/econ-ark/HARK/blob/master/HARK/core.py#L149

I don't think Solvers are kinds of Models. But I could see how it would be useful to connect Solver types to Model types via type polymorphism.

https://www.upgrad.com/blog/polymorphism-in-oops/

**Comment by llorracc** [comment]
I am highly sympathetic with this objective.  I'm not sure a dict is the right thing to pass, though -- maybe a namespace?  We want to impose as little structure as possible on the object required, but allow it to have as much structure as might be appropriate for any conceivable problem.  For some problem types, for example, an aggregate growth factor might be a single scalar (an infinite horizon model).  For others it might be a list (a life cycle model with an annual age profile).  For others it might be a nested list (a life cycle model with nested quarterly cycles).  For yet others it might be a scalar with a nested list (a quarterly model in an infinite horizon context).  Rather than trying to think of all the possibilities and design a data structure that has a pre-ordained structure for each possibility we have thought of, it would be better to pass some object which the code will know contains the time specification, and for that object to be able to respond to a query about what its type is, and then for other code to know how to use an object of each time specification type.  This will allow us to mix and match.

**Comment by mnwhite** [comment]
Dictionaries can handle all of that. They're just keys and pointers to
existing variables (other than immutable types, like int and float).

**Comment by sbenthall** [comment]
I agree with @mnwhite on that.

"Namespace" refers to a kind of [information organization](https://en.wikipedia.org/wiki/Namespace), which can be hierarchical. It is a coding pattern or an architecture.

"Dictionary", in Python, is a primitive data structure. It has certain properties, such as O(1) lookup, and built-in functionality.

Dictionaries can be used to implement namespaces, as we have done.

I think what you are getting at, @llorracc , is that you want flexibility in the temporal structure of a problem definition, and that you want this to be matched by the solver. But there are key things that are common the way problems and solvers work together, which would be their _interface_.

If you want to use the same _interface_ for objects with different internal structures, then that same interface is adaptable to _many forms_, which is where _polymorphic typing_ comes in.

In a more strongly typed programming language, such as OCaml, this sort of thing would be enforced by the language compiler and so something we would have already thought through carefully.

But Python is not strongly typed and so we haven't had to think carefully about this in the design yet. More rigorous thinking and design about the type system of HARK would help solve these issues around temporal structure of problems.

**Comment by llorracc** [comment]
I'm quite willing to believe that dicts can accomplish what we want.  

But the point was not specifically about the temporal structure of problems; that was an example.  Other aspects of a problem might have similar complexities, with multiple dimensions with different characteristics.  The point is that we do not want to prespecify the structure of a parameters object in a way that either requires users to create and pass parameters that are useless for their model, or makes it difficult or cumbersome to modify the model (say, by adding a state variable).  

I guess my sense is that python already has a phenomenally sophisticated set of tools for passing arguments among instances of classes; we ought to think carefully about how anything we do might constrict the possible future uses of the code we write.

**Comment by alanlujan91** [comment]
If I understand this correctly, this is the relevant part of the code

`solve_dict` is created from `time_vary` and `time_inv`:

https://github.com/econ-ark/HARK/blob/f338c976c813991a095a0d3fea9967232ea59e07/HARK/core.py#L1005-L1006

But then, these are "matched" against `solver_args`, which is a list of the args the solver expects. 

https://github.com/econ-ark/HARK/blob/f338c976c813991a095a0d3fea9967232ea59e07/HARK/core.py#L1020-L1032

However, this is built by observing the args that are explicitly named in the solver `__init__`: 

https://github.com/econ-ark/HARK/blob/f338c976c813991a095a0d3fea9967232ea59e07/HARK/core.py#L1068

Removing the enumeration of parameters from the solver `__init__` and leaving just a dictionary would cause a problem when creating the match. One solution is to remove this matching process and to just send all of the `solve_dict` to the solver, but then we are not being careful to handle what arguments the solver actually needs to solve. 

I like the idea of matching `solve_params` and `solver_args`, however, as it gives us an additional check to make sure we have initialized all the parameters we need to solve the model. 

One suggestion that comes to mind is creating a class attribute `solver_args = ["CRRA", "DiscFac", "solution_next", "IncShkDstn", ...]` for every solver to serve the function of `time_vary` and `time_inv` for the models. This way we can still match `solve_params` and `solver_args`, be explicit about what parameters a solver requires, and reduce the long list of inputs required to be passed one by one.

**Comment by sbenthall** [comment]
I think you are suggesting that we replace 

```
get_arg_names(solver_class.__init__)
```

with a class attribute

```
solver_args = ["CRRA", "DiscFac", "solution_next", "IncShkDstn", ...]
```

One thing I do not like about the current HARK design is how often it uses these lists of model elements (i.e, `state_vars`, `time_vary`, etc.) when in my opinion it would be better software design if this information were encoded in the software object and then accessed through inspection. The `get_arg_names` version is closer to what I think would be ideal.

Have I missed something about why use of `get_arg_names` is a problem?

**Comment by alanlujan91** [comment]
Doesn't `get_arg_names` make it so that I have to enumerate the parameters 1 by 1 in the `__init__` declaration (as above)?

**Comment by sbenthall** [comment]
Yes. `get_arg_names` is looking at the argument names for that function.

What is the motivation for having that `init` method not name its arguments?

**Comment by sbenthall** [comment]
Continuing on the theme of typing as a solution here...

Suppose we added type annotations to the Models, their parameterizations, or the Solver arguments.

Suppose this type information encoded (a) temporal structure, (b) other structural differences.

The type signature is discoverable through inspection:
https://docs.python.org/3/library/inspect.html#inspect.signature

Then a corresponding structure (i.e, the solver for a particular model) could be defined in terms of the same type annotations.

Then, the super- or abstract- classes for these objects can be type agnostic, knowing only that the type signature of the model and the solver have to match.

**Comment by llorracc** [comment]
> One thing I do not like about the current HARK design is how often it uses these lists of model elements (i.e, `state_vars`, `time_vary`, etc.) when in my opinion it would be better software design if this information were encoded in the software objects and then accessed through inspection.

Very much agreed -- kind of what I was trying to say above.

In struggling with my HARK 2.0 pre-alpha, I spent an inordinate amount of time trying to work around these problems.

Something I wanted to do there was to make a distinction between "solver" tools and "solution" objects.  

I also wanted to guarantee that any "solution" always had a complete specification of the problem to which it was a solution.  

In principle, it is possible to build a solution object that contains a problem and its solution, but without specifying a method by which that solution is obtained.  (For example, if the model is one with an analytical solution, no computational solver would be necessary).  

But generically, one would generally want a solver to start with a problem as specified in a "solution" object that had been configured with a particular problem, and add to that a solution method.  So I set things up so that the solvers were a subclass of a solution object.  Of course, this allows one to use as many different solution methods as one likes to generate a solution to a particular model.  But it guarantees some uniformity in the structure of those solutions.

**Comment by sbenthall** [comment]
> So I set things up so that the solvers were a subclass of a solution object.

I think this is close to the right answer, in that it connects the type of the solver to the type of the solution.
But of course, solvers are not a type of solution. So that's not good modularity.

I think maybe the right answer here is to use a generic type:
https://docs.python.org/3/library/typing.html#user-defined-generic-types

Generic types are a way to have a type that is in some sense about another type.

A classic example would be, in a strongly typed language, that you don't have a List type. You have a List[T] generic type.
Any particular list has to fill in the T variable with another type. So you would define List[T] once, then instantiate a List[String], and everything just works.

If the relevant structural aspects of a problem were its type S, we could then define Solution[S] and Solver[S] as generic types.

**Comment by llorracc** [comment]
> I think maybe the right answer here is to use a generic type: https://docs.python.org/3/library/typing.html#user-defined-generic-types
> 
> Generic types are a way to have a type that is in some sense about another type.

That sounds reasonable.  Does a "type" allow the full panoply of attributes that a class allows?

PS.  My approach was motivated in large part by the goal of preserving compatibility with the existing codebase.

**Comment by sbenthall** [comment]
Here is a good explanation of the difference between types and classes:

https://stackoverflow.com/questions/468145/what-is-the-difference-between-type-and-class/25114770

A "type" refers to the interface -- the specification of input and output rules -- of an object.
A "class" specifies implementation details. Many classes can have the same type.

I hope to take some time in February to write up a proper architecture proposal based on these and other recent discussions.

**Comment by alanlujan91** [comment]
See #1108 for an alternative that I quite like. Using `dataclass` I can enumerate parameters (with type hints), don't have to write a long `__init__` and then `self.param = param` for every param, and it keeps the functionality of `get_arg_names` intact.

**Comment by sbenthall** [comment]
I like this use of `dataclass`!
See #605 for an earlier discussion of how we might use dataclasses.

Looking more carefully at that documentation, it looks like, besides the free `__init__` method, dataclasses also support:
 - easy equality and comparator functions based on internal data. Useful for identifying convergence.
 - Easy __repr()__ methods to support inspection.

The most obvious use of dataclasses, in my view, is on solution objects, which currently are big data storage objects with frustratingly long __init__ methods.

But we could be using them much more extensively.
