### ISSUE TITLE
functional simulation tests to enable external distribution classes

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#1105]
Continuing from this discussion:
https://github.com/econ-ark/HARK/pull/1104#issuecomment-1017620775

I believe that @llorracc is keen on replacing as much of the distribution modeling functionality in HARK with an external library as soon as possible.

A major obstacle to doing this is that the tests for model simulations currently mostly check for near equality with specific numerical values, as opposed to testing for a functional relationship between a model's state value and prior relevant state values.

Fixing this is just a matter of labor time.

This would make it much easier to work on #611 #949

**Comment by sbenthall** [comment]
Though it's not entirely clear from the documentation, I've tested it and this `scipy.stats.rv_discrete` class is more full-featured that our current `DiscreteDistribution` class -- including CDF, entropy, moment, and _expected value_ computation -- with an initialization parameter, `values`, that mirrors the way we are currently constructing DiscreteDistributions.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_discrete.html

**Comment by llorracc** [comment]
Actually, I've spent a little time in the last couple of days looking into this and am glad to report that I think maybe the path forward is getting clearer, because sympy has recently put some effort into creating some tools that I hope we can build on for our purposes.  [Encouragingly, they started with what Mathematica had done](https://github.com/sympy/sympy/issues/16895), but seem to have ended up building something somewhat simpler, which may be subject to future improvements.  There is also an excellent treatment of the topic on the quantecon site, https://python-advanced.quantecon.org/stationary_densities.html.  

I also came across [this recent paper](https://arxiv.org/pdf/2112.14315.pdf) which claims to have made some fundamental advances in the efficiency of simulating Markov processes.

One thing that is somewhat confusing about this whole area is where exactly the boundaries lie between Markov chains and optimal control problems.  The math-stats people seem mainly to be interested in the question "give me some fixed Markov process, and I'll tell you all sorts of things about its consequences."  Optimal control people (and, mostly, economists) are interested in the question, "tell me the environment someone is in, and I want to figure out the optimal behavior."  Once optimal behavior has been figured out, maybe that gives you some fixed coefficients that can then be represented in a Markov chain, but the Markov chain part of it is in a sense easier than the 'find the optimal behavior' part.  Still, the common element to all of them is that we need to find a robust way to state what the environment is and how it evolves in response to exogenous and endogenous variables; maybe the new sympy objects will be useful for that.

**Comment by sbenthall** [comment]
An example of the kind of test that needs to be changed:

https://github.com/econ-ark/HARK/blob/master/HARK/ConsumptionSaving/tests/test_IndShockConsumerType.py#L92

And example of the kind of test it should be changed into:

https://github.com/econ-ark/HARK/blob/master/HARK/ConsumptionSaving/tests/test_ConsPortfolioFrameModel.py#L153-L156

**Comment by llorracc** [comment]
I have no objection to ADDITIONAL tests like https://github.com/econ-ark/HARK/blob/master/HARK/ConsumptionSaving/tests/test_ConsPortfolioFrameModel.py#L153-L156

And if the reason you think the first test should be eliminated is that it tests the outcome for a specific agent (at index 1), I'm on board.  Instead, what we should be testing is things like whether the average level of assets in simulations matches some raw number like 0.184 (or whatever the correct answer is).

Any time a change in the HARK code causes our simulations to produce significantly different quantitative answers, we need to be alerted to that because we know that our current code produces the right answers and any substantial change in those answers means the HARK change introduced a conceptual error somewhere (even if accounting identities remain satisfied).

**Comment by sbenthall** [comment]
Yes, the simulation tests I'm referring to are those that test a specific value for a specific agent.

We also have tests for the solution objects, which should not break with a change in how distributions are sampled. I.e. that the consumption function, for some amount of market resources, is 0.184. So these can go untouched.

I don't recall if we have any tests for the approximate equality of a simulated population mean to a fixed number. I would be wary of such tests, because the sensitivity of the equality approximation would need to be calibrated to the confidence interval of the result somehow to be effective if the only change was to distribution sampling.

**Comment by llorracc** [comment]
> I don't recall if we have any tests for the approximate equality of a simulated population mean to a fixed number. I would be wary of such tests, because the sensitivity of the equality approximation would need to be calibrated to the confidence interval of the result somehow to be effective if the only change was to distribution sampling.

Any such tests should be low precision ones.  If an aggregate variable changed from 3.14 to 3.15 or 3.13 we would not worry.  But if it changed to 6.8 or something, that would be a clear sign of a bug.

**Comment by sbenthall** [comment]
I'm taking responsibility for this issue, but am a little stuck.

One thing we could do is remove any tests for particular values that come out of a simulation's results.

In many cases, this would leave simulations as entirely untested except to show that they executed without error.

I wonder if there's anything else that comes to mind for what would be a good simulation test.
(The tests of a particular transition function are one idea, though writing these will be a cumbersome process.)
