### ISSUE TITLE
Necessity to check the conditions for nondegenerate solutions in ConsIndShockModel

### ISSUE THREAD

**Issue by derinaksit** [econ-ark/HARK#111]
ConsIndShockModel should be updated in a way that it checks the conditions for nondegenerate solutions and reports whether a solution exists under the given parameter values. For example, if the user asks HARK to solve a buffer stock model for which the Finite Value of Autarky condition fails, the code should report back a warning like "under the given parameter values, it is known that no nondegenerate solution exists" with a link to the relevant theoretical literature. I will prepare a pull request to add this feature.

**Comment by mnwhite** [comment]
Yes, this would be good.  Per our in-person conversation, this should be a method for the perfect foresight type and the ind-shock type (which extends the former). Because it will be inherited by child classes but might not be applicable/correct, it would be wise to put in dummy methods for child classes that raise an error when called.  See ConsIndShockModel.KinkedRconsumerType.makeEulerErrorFunc for an example.

**Comment by mnwhite** [comment]
Addressed in #115
