### ISSUE TITLE
BilinearInterp does not work when y_list is 1 element. 

### ISSUE THREAD

**Issue by alanlujan91** [econ-ark/HARK#1130]
This sounds not very interesting, if y_list is only 1 element, it should use LinearInterp. 

However, in models where one of the dimensions is income (TranShk), if we wanted to see the effect of perfect foresight on a particular model (TranShkStd = 0.0, TranShkCount = 1), this would not be possible unless rewriting a lot of code. 

BilinearInterp should be able to default to LinearInterp if y_list is 1 element, and this would allow to experiment with more complex models with Perfect foresight by shutting down income uncertainty. This might be relevant to the Labor models on HARK although it came up on my own work.

**Comment by mnwhite** [comment]
I think this would do more harm than good. If the user asks for a
BilinearInterp, they should get a BilinearInterp, not another class. It's
probably better to specify that x_list and y_list should have at least two
elements to be properly specified. In my own projects, I sometimes have
"fake" 2D and 3D interpolators that have 2 points of support in one (or
more!) dimension, [0., 1.]. For example:

`Fake3Dfunction = BilinearInterpOnInterp1D(2*[2*[ActualFunction]], [0.,
1.], [0., 1.])`

Here, the R^3 --> R function we want is constant with respect to y and z,
but some (not shown here) code expects it to take 3 arguments, because *in
general* this sort of object does depend on x,y,z. Maybe it's a terminal
solution or other semi-trivial case. We can represent this with an Interp1D
called ActualFunction (R --> R) replicated in a nested 2x2 list. We then
pass trivial grids for y and z, and we get the function object that we
want, which has all the behaviors we expect.

If you want something like TranShkGrid to work correctly even when there's
no transitory shocks (in a labor supply model where TranShk is a state
variable), all you need is a two-line fix:

if np.all(TranShkGrid == TranShkGrid[0]):
    TranShkGrid = [0., 1.]

**Comment by alanlujan91** [comment]
I can see how that could work... so even if I set f_values[:, 0]  = 0.0 ( for TranShk == 0.0 or any other "fake" point) BilinearInterp should give the correct result for TranShk == 1.0 if those f_values are correct?

**Comment by mnwhite** [comment]
Yes, but why not just tile the f_values, so they're the same for y=0 and
y=1 (or whatever you use), which would make the function return the same
value for f(x0,y) no matter the value of y?

**Comment by mnwhite** [comment]
Also, if you want all of this to be automated within the solver for
compatibility with TranShkStd=0, that's an argument for having the
distribution discretization functions *not* collapse a trivial distribution
down to 1 point. If someone asks for the 5 point equiprobable approximation
to a mean one lognormal with zero standard deviation, they should get a
discrete distribution with 5 points of support, each with probability 0.2
and value 1.0. Someone might have code that expects the behavior, "I asked
for N points in the distribution, I get N points in the distribution."

I raise this because I think someone proposed (or actually did?) change
this behavior recently.

**Comment by mnwhite** [comment]
Closing because this discussion was resolved.
