### ISSUE TITLE
Simulation code cannot allow for *age* varying interest rates

### ISSUE THREAD

**Issue by Mv77** [econ-ark/HARK#1132]
Some time ago, @wdu9 highlighted [an issue](https://github.com/econ-ark/HARK/issues/1106) with the simulation code that prevents age-varying interest rates from being used.

For *age* varying interest rates, the fix is very simple as @mnwhite and I suggested in that thread:
- Add Rfree (and Rboro?) to `time_vary`.
- Edit `get_Rfree()` appropriately.

But the issue turned out to be that Will wanted not age-varying but time-varying interest rates. This is much trickier and the discussion spurred plans to separate time and age in HARK and to make [the default rate of return risky](https://github.com/econ-ark/HARK/issues/1107).

Agree with the plans or not, there is still a very easy fix for *age-varying* rates, which we don't have yet ([this PR does not achieve that, but something else](https://github.com/econ-ark/HARK/pull/1110)).

An external user emailed me yesterday requesting this feature. I don't have the time to fix it myself in the next two weeks.

**Comment by alanlujan91** [comment]
There are still some blocking issues in #1108 that I am trying to work on this week. That PR adds agent type `IndShockRiskyAssetConsumerType` with an *age_varying* interest rate, which essentially merges the functionality of `IndShockConsumerType` and `PortfolioConsumerType`. 

@Mv77 did the external user request this feature for `KinkedRConsumerType` (since you mentioned `Rboro`)? The current changes I'm working on would not affect this type, since it does not use `Rfree` but instead uses `Rboro` and `Rsave`.

**Comment by alanlujan91** [comment]
@Mv77 @wdu9 does time/age varying Rfree in simulation works now or is this still outstanding?

**Comment by Mv77** [comment]
I believe your recent changes should have fixed this, right?

Rfree can now be a list and goes into time_vary? If so, this has been addressed.
