### ISSUE TITLE
CobbDouglasEconomy - only allows default parameter values

### ISSUE THREAD

**Issue by kwkak37** [econ-ark/HARK#1135]
**Describe the bug**
For HARK/ConsumptionSaving/ConsAggShockModel.py, the CobbDouglasEconomy subclass does not seem to solve using my custom parameter values.

**To Reproduce**
I assign parameters and solve for the AggShockConsumerType agents, and then solve the CobbDouglasEconomy with the AggShockConsumerType agents. For example, I can assign a CRRA value of 4.0 for CobbDouglasEconomy.

**Expected behavior**
For example, when I solve for the aggregate rental rate and aggregate wage rate using "calc_R_and_W()", I expect to calculate using my CRRA value of 4.0. Instead, it always lists the default parameters, including the default parameter value of CRRA = 2.0.

**Desktop (please complete the following information):**
 - Econ-ARK and Python version [eg. 0.10.6 and python 3.8.8]

**Comment by mnwhite** [comment]
Can you provide a code snippet rather than a description? The CRRA value
given to a CobbDouglasEconomy isn't used during the iterative solution
method, only in choosing an initial state for the simulation. If you look
at the code for calc_R_and_W, it neither directly nor indirectly calls on
self.CRRA; it only uses the parameters CapShare and DeprFunc. The CRRA
parameter *of the economy itself* is only used in the update method when
computing the steady state capital-to-labor ratio in a perfect foresight
(riskless) version of the model. That's only used for initializing the
wealth of agents in the simulation, so the economy starts out (reasonably)
near the "right" level for models with risk. Changing CRRA on a
CobbDouglasEconomy should only change the solution to the model due to
numeric error (different initial conditions can lead to a very marginally
different solution).
