### ISSUE TITLE
Creating an environment from an environment.yml file

### ISSUE THREAD

**Issue by alanlujan91** [econ-ark/HARK#1167]
It's not currently possible to do `conda install --file requirements.txt`. The output is 

```
>conda install --file requirements.txt
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - sphinx-rtd-theme
```

Alternatives are `pip install -r requirements.txt` or `pip install -e .`. 

If you want to use packages from conda however you have to install them by hand, and ignore the ones that are only pip packages. An alternative to this could be `conda env create -f environment.yml` where the `environment.yml` file looks something like this

```
name: hark-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - sphinx
  - future
  - joblib
  - dill
  - scipy
  - flake8
  - nbsphinx
  - seaborn
  - recommonmark
  - interpolation>=2.2.3
  - numba
  - quantecon
  - pandas
  - networkx
  - xarray
  - jupyterlab
  - jupytext
  - pip
  - pip:
    - sphinx-rtd-theme
 ```

I'm not sure if all the dependencies listed are available in conda, but the point is that an `environment.yml` file can enumerate the conda packages and the pip-only packages, and create a full conda environment with 1 command. 

See https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file

**Comment by llorracc** [comment]
@MridulS,

I'm hesitant to adopt this new way of doing things because conda can be SO SLOW -- and not infrequently fails altogether.  

My recollection is that you said at some point the slow code in `conda` will just be replaced by the fast code in `mamba.`  But I gather that has not happened yet?  Maybe when it does we might embrace this way of doing things.

PS.  At the NumFocus summit, let's make a point of connecting to the JupyterLab development team and asking them what best practice is for constructing notebooks with their own requirements.txt specs.  

PPS.  Also, we should think about whether to move to JupyterBook format, at least for our `REMARKs`

**Comment by alanlujan91** [comment]
It's not necessary that this be the default way to set up and/or install an econ-ark (dev) environment, but simply an additional way for those of us who prefer conda management, even if we use mamba for speed.
