### ISSUE TITLE
API documentation not showing up on the site 

### ISSUE THREAD

**Issue by dedwar65** [econ-ark/HARK#1223]
The API documentation was showing up on the site about 2-4 weeks ago. Today, each of the links are completely blank (I've included some screenshots of both the "Tools" and "Models" subsections.)

[Blank API - ConsPortfolio.pdf](https://github.com/econ-ark/HARK/files/10579816/Blank.API.-.ConsPortfolio.pdf)
[Blank API - distribution.pdf](https://github.com/econ-ark/HARK/files/10579817/Blank.API.-.distribution.pdf)

**Comment by llorracc** [comment]
Hmm, I just went to `hark.readthedocs.io` and it seemed to be rendering fine for me.

And both of the links above worked for me as well, at least in resulting in the download of a PDF.

Can you give the exact link that is not working for you?

**Comment by dedwar65** [comment]
Here are the two links that I posted a pdf for:

https://hark.readthedocs.io/en/latest/reference/tools/distribution.html

https://hark.readthedocs.io/en/latest/reference/ConsumptionSaving/ConsPortfolioModel.html

**Comment by alanlujan91** [comment]
Can confirm, none of the links under this section load anything

**Comment by sbenthall** [comment]
I'll take a look at this.

**Comment by sbenthall** [comment]
API docs build works locally. Checking RTD logs.

**Comment by sbenthall** [comment]
Error shows up only on `latest` build for RTD, not on `stable` build (tied to 0.12)

**Comment by sbenthall** [comment]
Failing Sphinx logs on `latest`:
https://gist.github.com/sbenthall/2444d5f99ef83247033ef2f84d949fc9

Working Sphinx logs on `stable`:
https://gist.github.com/sbenthall/d39ad66a5c10006e38cc31bb22473e06

The failure is due to Python modules not loading properly due to an import error:

```
Failed to import 'HARK.distribution': no module named HARK.distribution
```

```
WARNING: autodoc: failed to import module 'distribution' from module 'HARK'; the following exception was raised:
cannot import name 'rv_continuous_frozen' from 'scipy.stats._distn_infrastructure' (/home/docs/checkouts/readthedocs.org/user_builds/hark/envs/latest/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py)
```

And likewise for many other modules...

```
WARNING: autodoc: failed to import module 'ConsumptionSaving.ConsIndShockModel' from module 'HARK'; the following exception was raised:
cannot import name 'rv_continuous_frozen' from 'scipy.stats._distn_infrastructure' (/home/docs/checkouts/readthedocs.org/user_builds/hark/envs/latest/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py)
```

`scipy`  v.1.7.3 is being installed in the RTD build environment with Python 3.7:
```
Collecting scipy
  Downloading scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
```

My local `scipy` install is Python 3.10, v1.9.0.

It looks like some time ago we decided to stop `officially` supporting Python 3.7:
https://github.com/econ-ark/HARK/pull/1142

Which means that there is some configuration issue where we haven't yet told RTD not to stop using 3.7

**Comment by sbenthall** [comment]
The fix involves setting a configuration option: https://blog.readthedocs.com/sphinx6-upgrade/

**Comment by sbenthall** [comment]
API autodocs for `latest` (`master`) are now working on RTD!

This took some finagling.
https://github.com/econ-ark/HARK/commit/0fc0f73845da43b5ee17ebdeb807af247aae5775

- The right option to set in .readthedocs.yml is `build.tools.python` and it is quoted; do not use `python.version`
- I tried using 3.11 and 3.10 for the RTD Python build, but both of these led to build failures due to upstream Python issues. 3.9 was the latest (highest valued) version I could find that worked.

Looks like the docs are quite sensitive to the dependency stack, so it's good to kick the tires on them.
Thanks @dedwar65 for catching the issue.

**Comment by llorracc** [comment]
@sbenthall, FYI, I've asked @MridulS to make a proposal to Google "Summer of Docs" this summer to have someone come in and overhaul our documentation.  @MridulS suggested a while ago that we should move to whatever system the cool kids are using (numpy, scipy, etc), and presumably that's something this person would implement.
