### ISSUE TITLE
vFunc and vPPfunc are sometimes Null Functions

### ISSUE THREAD

**Issue by DominicWC** [econ-ark/HARK#1452]
**Describe the bug**
If PerfForesightConsumerType or IndShockConsumerType are solved, their solution contains a function 'vPPfunc' with the type HARK.utilities.NullFunc. This function can't be plotted. This is likely an issue in several other models. 

For IndShockConsumerType specifically, vFunc is also a Null Function.

**To Reproduce**
```
from HARK.ConsumptionSaving.ConsIndShockModel import IndShockConsumerType
from HARK.ConsumptionSaving.ConsIndShockModel import PerfForesightConsumerType
agenta=IndShockConsumerType()
#agenta.cycles=0 #optional, these are here to show that whether the solution is a finite or infinite horizon doesn't matter
agenta.solve()
agentb=PerfForesightConsumerType()
#agentb.cycles=0 #optional, these are here to show that whether the solution is a finite or infinite horizon doesn't matter
agentb.solve()
print(agenta.solution[0].vFunc)
print(agenta.solution[0].vPPfunc)
print(agentb.solution[0].vPPfunc)
```

- OS: Windows 10
- Econ-ARK and Python: version 0.15.0, python 3.11 and 3.12

**Comment by alanlujan91** [comment]
`vFunc` requires `vFuncBool = True` and `vPPfunc` requires `CubicBool = True`

**Comment by DominicWC** [comment]
That fixes the IndShockConsumerType. The PerfForesightConsumerType still returns a null function for vPPfunc.

**Comment by mnwhite** [comment]
That's because there is no cubic spline interpolation for PerfForesight.
The *true* consumption function really is piecewise linear (often just one
line!), not smooth. So the marginal marginal value function is either
perfectly represented by the (numeric) derivative of the marginal value
function, *or* is actually a discontinuous function that we don't currently
have a way to represent.

Both LinearInterp and CubicInterp treat the function as continuous. We
would need to extend those classes to allow versions with "proper"
discontinuities. As is, discontinuities can be *approximated* by putting
back-to-back gridpoints that are (say) 1e-12 apart. You *can* put two
gridpoints right on top of each other, but it runs the risk of the function
being evaluated *right* at that point, which will return an error without
further intervention.

**Comment by alanlujan91** [comment]
@mnwhite should it throw an AttributeError then? "You tried to set an attribute that is not applicable to this setting."

**Comment by mnwhite** [comment]
*Maybe*. I'm mostly ok with users doing slightly risky things like that.

**Comment by DominicWC** [comment]
It seems like this is working as intended. I'll stick something about this in the documentation.
