### ISSUE TITLE
PEP 8 stylistic cleanup

### ISSUE THREAD

**Issue by apthorpe** [econ-ark/HARK#171]
Consider running [flake8](http://flake8.pycqa.org/en/latest/) against the code to improve readability and identify issues with missing and unused imports. flake8 identifies [PEP 8](https://www.python.org/dev/peps/pep-0008/) stylistic issues.

This is low priority, but something to consider for long-term code maintainability and readability.

I made a first attempt at reducing issues identified by flake8 in the main modules; see https://github.com/apthorpe/HARK/tree/master/HARK This isn't meant as a pull request as much as gauging interest in the stylistic cleanup effort.

FWIW, I was introduced to HARK at SciPy 2018 and thought I might contribute some effort toward software engineering tasks (testing, packaging, code review, Python 2/3 compatibility & conversion). I typically start with flake8 style cleanup because stylistic modifications shouldn't change the code functionality and it gives me an opportunity to read  through the code.

**Comment by brainwane** [comment]
@apthorpe Thanks for the suggestion, and for your interest in helping!

I'd be interested in using `flake8` or [black](https://github.com/ambv/black) or a similar tool to improve our formatting, and use automated testing to lock in the codebase against future linter errors. @mgerring @mnwhite @npalmer-professional do you have any preferences here? I suggest we go with `black` to favor decisiveness. :)

**Comment by npalmer-professional** [comment]
@brainwane I'm generally in favor!  However important caveat: in the past **some** code style decisions were made as compromises to make it easier for economists to follow some of the complicated math more easily.  That part is pretty vital, since the heavy-duty contributors will largely be economists/other researchers working on the complicated math parts of the code.

As with many things I think the answer will be "let's run both in different forks and eyeball the outputs." Ideally all the suggestions will not interrupt math-style-reading!

@brainwane what would it take to do what @apthorpe did, but with black?  I say we do that, then ping @mnwhite and @llorracc and see if we can get a quorum on one or the other.

**Comment by apthorpe** [comment]
I was not aware of black; I've been looking for a tool like that for
_years_. I'll start familiarizing myself with it ASAP.

Once there's a decsion made, I'm still willing to create a branch, do the
scut work, and submit a PR.

**Comment by mnwhite** [comment]
Yes, I'm in favor of style cleanup. We *tried* to be consistent with variable and function naming standards, and have a naming style guide at www.github.com/econ-ark/NARK ... It hasn't been touched in two years, and I don't think everything we do is consistent with it.

I swear there *is* a consistent naming convention in HARK, but some of it is merely my personal headcanon.

**Comment by mnwhite** [comment]
Also: Some very strong words are used in the NARK, like "PROHIBITED".  This is obviously not the case.

**Comment by llorracc** [comment]
athorpe, thanks for your help!  

Not only am I in favor of style improvements, I'm in favor of having a _policy_ about style, which is publicly posted (so that other people can help us abide by that style).  

Matt pointed you to the [NARK](https://github.com/econ-ark/NARK/blob/master/LaTeX/NARK.pdf) document, but that is more for economists defining naming conventions for commonly used variables in our models.  We do not have a well-defined set of guidelines for code (except that variable names should be consistent with the guidelines in the NARK).  

If you could help us define a style (maybe just by proposing that "econ-ark should post a link saying that its preferred style is [x] which will be enforced by [tool y]", then help update our code to that style, it would be even better than just suggesting specific code changes flagged by such a tool.

**Comment by brainwane** [comment]
@apthorpe thank you for the thorough response!

As you have perhaps gathered, we're in the midst of a few different overhauls with Econ-ARK, such as the Python 3 support we just landed. It would be great for you to join us in our Zulip asynchronous chat https://chat.opentechstrategies.com/#narrow/stream/16-Econ-ARK (I don't have your email address, otherwise I would create an account for you and send you an invite; feel free to create an account and join in the discussion).

Right now I think `flake8` is a better match for what we're doing because I see that `black` says it's not yet production ready, and it sounds like there are some outstanding questions they need to resolve.

I think a good way to start would be to create two different diffs against `HARK/core.py`, so we can get a feel for what `flake8` says needs fixing. One diff would be a minimal change to clean up only the most egregious problems that make the codebase actively hard to work with, and the other would use `flake8`'s full PEP 8 compliance toolset to make a fully compliant file. What do you think?
