### ISSUE TITLE
RuntimeWarning: All-NaN slice encountered

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#177]
This warning message crops up frequently, but whatever is causing it, the results never seem to be affected.  

It would be good if we could identify what is causing it and modify the code as appropriate so that the warning is no longer generated (if in fact the cause is innocuous).

**Comment by mnwhite** [comment]
This can happen when an array index is querried doesn't have any real data-- all of the qualifying elements are NaNs.  An alternate version comes up if you do np.mean(X[array_of_all_falses]), which says you're taking the mean of an empty slice (the average of zero numbers).

It might be something really deep down in one of the interpolation routines.  If you turn off the monkey patch to warnings (if that still exists), Python will tell you which line is generating the warning.

**Comment by shaunagm** [comment]
This warning is usually not a big deal and should be suppressed, so closing in favor of #247.  There are some circumstances where it could be a legit error, @pkofod will elaborate.

**Comment by pkofod** [comment]
I think the comment I had may have been a bit too specific to a problem I had implementing a specific function that should be tested on it's own either way, so I think that there really isn't much more to say here.

**Comment by Xiaoyu0131** [comment]
I am wondering if this issue is causing my while loop not exiting. To simplify my code, I am using

While (larger>thresh):
 larger = do_something

I get the warning:
RuntimeWarning: All-NaN axis encountered
  larger = np.nanmax([top_max,bottom_max,left_max,right_max]) 
which I think it means all the variables are NaNs that (larger>thresh) is not satisfied anymore. Checking the statement supported my guess: 
(larger >= thresh)
Out[820]: False
But my while loop keeps running. Even If I add 

If np.isnan(larger):
 break 

to the while loop, it still does not stop.
