### ISSUE TITLE
Documentation for MPCnvrs

### ISSUE THREAD

**Issue by Hergie** [econ-ark/HARK#189]
I am trying to understand the solution method in ConsIndShockModel. Could you provide some reference for the line:

`MPCnvrs      = self.MPC**(-self.CRRA/(1.0-self.CRRA))`,

included in method `defValueFuncs` within class ConsPerfForesightSolver? 

Is the derivation included e.g. in Carroll 2012: "Solution Methods for Microeconomic Dynamic Stochastic Optimization Problems"?

**Comment by mnwhite** [comment]
I'm not totally sure there *is* a citation for this line of math.  If there is, it would be in this paper (http://www.econ2.jhu.edu/people/ccarroll/papers/BufferStockTheory/) rather than those lecture notes.

To explain: In "ConsPerfForesight" model, there is no income risk and utility is CRRA.  In this setting, the consumption function is linear, and it can be calculated in closed form exactly (which is the approach the solver takes).  Moreover, the value function is "pseudo-linear" (not a real term), in the sense that if you compose the value function through the inverse utility function, the result is linear:

uinv(vFunc(m)) = a linear function

MPCnvrs represents the slope of the "pseudo-inverse value function" vFuncNvrs.  I did the math for that line about 3 years ago, and I don't think I have the notepaper on which I did it (I think I threw it out less than three weeks ago when moving houses).

Hopefully that's enough for you to try to reproduce the math for this line.  If not, I (or Chris) can take a stab at writing it up formally.

**Comment by llorracc** [comment]
I admit I'm kind of puzzled what this might be for -- it seems to be a mixture of several incommensurable things.  

$c^{-\CRRA}$ is always equal to marginal utility from the current level of consumption

$((1-\CRRA)v)^{1/(1-\CRRA)}$ is the (in the perfect foresight model, linear) function which, when raised to the $(1-\CRRA)$ power and divided by $1/(1-\CRRA)$ yields the value function.  

I'm guessing it might be an error -- an elision of a couple of different things, possibly caused by some kind of a copy-paste error or something.  Is it used anywhere?

**Comment by mnwhite** [comment]
Not an error, just a cryptically named variable.  See above.

**Comment by mnwhite** [comment]
If you are only trying to understand the solution for ConsIndShock, it's not necessary to work through this piece of math.  This method is overwritten or never called by the solver for ConsIndShock.

**Comment by Hergie** [comment]
Just adding that similar math is used in ConsIndShockSolver.solve() when constructing the value function as part of the solution (vFuncBool == True).

In that case `solve` calls `addvFunc`, which calls `makevFunc`, which has lines:

`MPCminNvrs   = self.MPCminNow**(-self.CRRA/(1.0-self.CRRA))`
`vNvrsFuncNow = CubicInterp(mNrm_temp,vNvrs,vNvrsP,MPCminNvrs*self.hNrmNow,MPCminNvrs)`

If I understand correctly, `makevFunc` inverts the value function calculated at gridpoints (`vNrmNow`) because this inverted object (`vNvrs`) is more suitable for interpolation (due to being more linear?) than `vNrmNow` itself. `MPCminNvrs` is used to define the intercept and slope of the limiting linear function of `vNvrs`. Once this interpolation is done, `makevFunc` finally inverts the result back to the actual value function (`vFuncNow`).

**Comment by pkofod** [comment]
> MPCnvrs represents the slope of the "pseudo-inverse value function" vFuncNvrs. I did the math for that line about 3 years ago, and I don't think I have the notepaper on which I did it (I think I threw it out less than three weeks ago when moving houses).

should we simply add a "slope" suffix then?

**Comment by mnwhite** [comment]
Yeah, renaming this is fine. It's super cryptic as is.

**Comment by shaunagm** [comment]
Did this get renamed, or is this still an open issue?

**Comment by llorracc** [comment]
I've finally addressed it.  

The necessary derivations were not really anywhere in the documentation, so I have added them to 
[BufferStockTheory](http://econ.jhu.edu/people/ccarroll/papers/BufferStockTheory), [SolvingMicroDSOPs](https://econ.jhu.edu/people/ccarroll/SolvingMicroDSOPs), and [PerfForesightCRRA](http://econ.jhu.edu/people/ccarroll/public/lecturenotes/consumption/PerfForesightCRRA).  I have changed the name of the MPCnvrs variable to vFuncInvSlope in HARK, and added both a bit of an explanation and some links in the docstring for the PerfForesightConsumerType method in ConsIndShockModels.  Finally, I have updated the PerfForesightConsumerType DemARK to explain things better.  

I'll ask @mnwhite to review the (tiny) changes to HARK core.

**Comment by mnwhite** [comment]
I'll take a look at this, but the variable name should probably have Nvrs
in it, rather than Inv, as that's our abbreviation for pseudo-inverse.

And yeah, this is one of those pieces of math that Chris probably did years
ago, but never wrote down. I worked it out myself on a scrap of paper at
the CFPB in fall 2015, but also never typed it up. The classic "exercise
left for the reader"...

**Comment by llorracc** [comment]
Probably I did do it years ago; I must have done so if it was in the Mathematica code.  But running it down again, it took me forever to rediscover the key fact which is that $\kappa^{-1}_{t} = \mathbb{C}_{t}$ which is really pretty cool.  

PS.  I think actually I did call it vFuncNvrsSlope -- the name in the original message was a typo.
