### ISSUE TITLE
setAndUpdateValues method

### ISSUE THREAD

**Issue by nomadj1s** [econ-ark/HARK#192]
Thank you for providing HARK. I am trying to work my way through the ConsIndShockModel.py example. I have a question about the setAndUpdateValues method, defined on line 664, under the ConsIndShockSetup class. The method takes apart the IncomeDstn list, but I am getting an error when I try to replicate the method step-by-step.

Specifically, I do the following:

1. First, I create an instance of the idiosyncratic shock consumer type: 
   `tester = IndShockConsumerType(**Params.init_idiosyncratic_shocks)`
2. Line 693, under setAndUpdateValues, is as follows:
   `self.PermShkValsNext  = IncomeDstn[1]`
3. However, if I try to run a similar command manually:
   `tester.IncomeDstn[1]`
   I get the following error:
   ```python
   Traceback (most recent call last):

   File "<ipython-input-60-d66a500b81d3>", line 1, in <module>
     tester.IncomeDstn[1]

   IndexError: list index out of range
   ```
4. If I run the following command, there is no error:
   `tester.IncomeDstn[0][1]`
   This is because IncomeDstn appears to be a list inside of a list (if that makes sense).
5. Elsewhere in the file, on line 1901, the calcBoundingValues method appears to use the "expected" indexing:
   `PermShkValsNext   = self.IncomeDstn[0][1]`

My question: why does the setAndUpdateValues method work? I have tried to trace all the steps that lead to that method, but I don't see anywhere where the IncomeDstn attribute is "stripped" down to it's inner list before being passed to the setAndUpdateValues method. How come there is an error when I run the command on line 693 manually, but not when the entire code is run?

**Comment by mnwhite** [comment]
Hi, welcome to HARK!

Short answer: The "missing" step where `tester.IncomeDstn[0]` in your test becomes `self.IncomeDstn` in the solver code is in HARK's built in `solve` method.

Long answer: First, note that `self` in the solver code and the thing that you're calling `tester` are *different* objects of *different* classes.  Your `tester` is a representation of the agents themselves: an instance of `IndShockConsumerType`.  This agent class' `solveOnePeriod' function is called `solveConsIndShock', whose code (other than function/input definition and docstring) is a whopping 5 lines long.  When called, it merely creates an instance of ConsIndShockSolver, executes a couple methods, and returns the result.  As you've found, all of the actual work happen inside of methods of ConsIndShockSolver (and its parent classes).

When the `solve` method of an `AgentType` subclass instance is called, HARK loops through the periods of that agent's "cycle", feeding the correct inputs to the one period solver for each period.  That is, the information in `tester.IncomeDstn` is not passed directly to `solveConsIndShock`, only `tester.IncomeDstn[t]`, where `t` is a time index that HARK is looping over.

The inputs to the "one period solver function" for each micro model in HARK are partitioned into time-invariant inputs (named in `time_inv`) and time-varying inputs (named in `time_vary`); note that `time_vary' also includes other attributes that vary over time, but are not passed to the solver.  One of the elements of `time_vary` for instances of `IndShockConsumerType` is `'IncomeDstn'`, so HARK treats that attribute as a time-varying list of one period values, rather than the same thing every single period.  In contrast, `time_inv` includes (inter alia) `'CRRA'`, so the entire contents of `tester.CRRA` (2.0, in the example) are passed to the solver every period.

At this point, you might be asking, "Wait, what do you mean 'cycle' of periods?  It's an infinite horizon problem!"  HARK is set up to handle both infinite and finite (e.g. lifecycle) horizon variations of models.  The integer-valued attribute `cycles' indicates the nature of the problem for a particular instance: `cycles=0` means it's an infinite horizon problem whose cycle of periods should repeat until convergence when solving; `cycles=1` means it's a lifecycle problem whose cycle of periods runs once from beginning to end; `cycles=N` means the cycle of periods runs N times cyclically.

The solver inputs named in `time_vary` should be lists of the same length, also stored in the attribute `T_cycle' in some (all?) models.  In the example you're looking at, the "cycle" is only one period long, with `cycles=0`: the agent lives out the same "kind" of period over and over again until they die.  Other included examples show how to set up simple lifecycle models, as well as infinite horizon problems with (say) a four period "season" cycle.

Let me know if this explanation helped, or if you have other questions.

**Comment by nomadj1s** [comment]
Great, I totally follow what you are saying. If this weren't an infinite horizon model, tester.IncomeDstn might have a different distribution for each period, t, but in my case, there is only one period needed, hence the "list inside of a list."

So, I suppose, this line is grabbing the one income distribution:

```python
solve_dict[name] = eval('agent.' + name + '[t]')
```
Thank you for the prompt response!

**Comment by mnwhite** [comment]
That's exactly it.  And that line really ought to be rewritten as:

`solve_dict[name] = getattr(agent,name)[t]`

I wrote the core HARK code before I was very familiar with Python, and used bad style in a few (read: many) cases.

**Comment by mnwhite** [comment]
Closing issue, might apply some tag about "issues encountered by newcomers" or "learning HARK" so discussions like this can be easily recovered.
