### ISSUE TITLE
“double_scalars” error 

### ISSUE THREAD

**Issue by derinaksit** [econ-ark/HARK#218]
Whenever the cstwMPC code is run, "invalid value encountered in double_scalars" warning appears. Accordingly, the MPC of the unemployed and retired are reported as NaN. Oddly, this does not affect the average MPC calculation.

**Comment by mnwhite** [comment]
If you're running the perpetual youth specification, it is correct for the printed output to report that the average MPC of the retired is NaN-- there is no retirement, so it's reporting the mean of an empty slice.

The average MPC of the unemployed should exist in perpetual youth *unless* you set IncUnemp = 0 *and* agents start with exactly aNrm=0.  Then you'll have people who are unemployed in their first period of life and have mNrm=0, so their MPC doesn't exist (it exists in a right derivative sense).  So that might be happening.  It would also happen if you turned off unemployment and had UnempPrb = 0.

I'm going to convert cstwMPC into a REMARK, so there will be a cleaning and checking pass.

**Comment by derinaksit** [comment]
I set IncUnemp to 0.15 and UnempPrb to 0.07, so there should be an average MPC for the unemployed. 

I agree that the MPC for the retired should be NaN, so ignore my "Accordingly, the MPC of the unemployed and retired are reported as NaN." point. 

I suspect the source of the problem might be different since this “double_scalars” error started to occur after the HARK became python 3 compatible. If you download HARK and run cstwMPC, you get 3 “double_scalars” errors: for the unemployed MPC, for the retired MPC and "hand_to_mouth_pct.append(np.sum(temp_weights[in_top_third_MPC == q])/hand_to_mouth_total)”.

**Comment by llorracc** [comment]
Yes, that's an example.  Matt says he will fix it when he gets around to a cleanup project on cstwMPC.  In the meantime, I have asked Derin to find a way to capture the error and suppress it, since it does not affect his results and is only confusing to a new user of his code.

**Comment by mnwhite** [comment]
There is no error, only a warning.

**Comment by pkofod** [comment]
> There is no error, only a warning.

We *could* use `filterwarnings`. The only problem is of course, that then it might go unnoticed if a change introduces some "bad" warnings (some that actually represent a problem).

**Comment by mnwhite** [comment]
Yeah, I think we might have to be "good" about this and specifically
designate areas of the code where we want to ignore the warnings (e.g. NaNs
that we meant to be there, or are corrected 2 lines later).

**Comment by shaunagm** [comment]
Looks like this is part of [the broader discussion around when to suppress warnings](https://github.com/econ-ark/HARK/issues/247 ), so I'll close this issue and we can take the discussion there.
