### ISSUE TITLE
Local vs global suppression of warnings

### ISSUE THREAD

**Issue by mnwhite** [econ-ark/HARK#247]
In the latest / immediately pending release, we effectively suppressed all numpy warnings.  New users were apparently alarmed by all these warnings, even though they were harmless and were popping up from intended operations.

Per discussion among CDC, MNW, PKM, SGM: We should go through the code and *locally* suppress these warnings when we know they come up and are harmless.  As is, we are "indiscriminately" suppressing warnings, which might hide relevant information from users as they write/test new code.

**Comment by MridulS** [comment]
https://github.com/econ-ark/HARK/blob/9f1c19fcc8fa89680c9478811f9b92a62479d853/HARK/distribution.py#L128-L138 seems like  the only place where warnings are suppressed in the codebase. Maybe we can catch just this RuntimeWarning to make this more localised.

Also the warning comes from `np.log(zBot)` (zBot =0) rather than `erf(infty)` which seems to be `1.0` according to scipy.

**Comment by mnwhite** [comment]
We can also just hardcode the fix for this, manually checking for zBot==0
and filling in appropriately.  It will make the code take like a fraction
of millionth of a second longer, but this function isn't called that
often.  It probably takes more cycles to handle the warning.
