### ISSUE TITLE
tractable buffer stock problem with graph - fixed CRRA parameter

### ISSUE THREAD

**Issue by kubapawelczak** [econ-ark/HARK#369]
While playing with parameters in Tractable Buffer Stock I noticed that CRRA parameter is fixed in last section  in line :"CRRA = fixed(4),"  In order to allow users to work with different utilities it should be just normal variable

**Comment by llorracc** [comment]
Thanks for posting this issue (I think in response to my request in class).  Having thought about it, I've now realized that leaving out the CRRA was intentional; it was a useful thing to show the class how to add or subtract controls.

But now that you have posted an issue, you know how to do it, so please post other issues if they come to your attention!
