### ISSUE TITLE
what stays in HARK and what goes to DemARK/REMARK

### ISSUE THREAD

**Issue by MridulS** [econ-ark/HARK#415]
As discussed during the calls we need to decide what stays in and out of HARK

simulation, parallel, interpolation may be deprecated in the future

Like cstwMPC and cAndCwithStickyE needs to be independent REMARKs
https://github.com/econ-ark/HARK/pull/334
https://github.com/econ-ark/HARK/pull/335

**Comment by llorracc** [comment]
cstwMPC and cAndCwithStickyE already are independent REMARKs.  

The main sticking point in removing them from main HARK is that at least one of them (cstwMPC) is used as a tool in at least one (and maybe more than one) DemARK.  

Furthermore, I want to enable that functionality more generally.  

I think that @shaunagm and @sbrice and I have decided that when we reorg the repos, we are going to make REMARK and DemARK be submodules (I don't know if we've decided where).  If the REMARKs are submodules, then a DemARK using tools from a REMARK should be able to predict where those tools will be.  At that point we can remove them from the main HARK paths.  

PS.  I'm a little worried about this strategy, though, because I found a few days ago that when I cloned a repo that had another repo as a submodule, in my local clone the contents of the submodule were _not_ cloned.  At a minimum, that means that we will need to find a way to make sure that when someone pip/conda installs econ-ark, the contents of the REMARK and DemARK submodules do get included.

**Comment by mnwhite** [comment]
The pieces of cstwMPC that are used in DemARKs are *extremely* small-- a
single function that's like 4 lines long and a set of parameters.  I think
it's ok to simply put that function into the DemARK, along with the
parameter dictionary.

**Comment by llorracc** [comment]
Well, but I have also had several students who did projects where they were asked to use elements from cstwMPC and cAndCwithStickyE and then modify them.  I would therefore like to have an example of generically how that is done, partly as a teaching tool.  So, I'd rather _not_ just copy stuff, unless it turns out to be harder than I think to set things up as described above.

**Comment by shaunagm** [comment]
I don't think it makes sense to determine the architecture of our repositories based on having a useful teaching example.  I would recommend creating a little snippet of code that shows what you want for your students - perhaps using a [gist](https://gist.github.com/), if it's really just a small example - and then make a simple copy of the code as Matt suggests.  I understand the desire not to duplicate code but you don't want to tie yourself in knots trying to avoid it.

**Comment by llorracc** [comment]
@shaunagm The idea is not to determine the structure of the repos for the teaching example.  It is that if we go with the repo structure we had already proposed for other reasons, then there will be no need to change the particular thing we are talking about in the DemARKs, because the DemARKs will still have access to the REMARKs via the submodule file structure.  So, that's why I propose we just wait to do this work until we restructure the repos.

**Comment by sbenthall** [comment]
REMARKs are, if I understand correctly, supposed to be pretty static. A replication or reproduction of some published paper should not change very much after the paper is published. It will probably need to have its HARK and other dependencies pegged to a particular version to guarantee reproducibility over time.

Whereas if software is being reused in contexts besides its original one, it is going to need to be refactored, broken into modules, and reworked. I'm bumping into obstacles just trying to get the [cstwMPC REMARK](https://github.com/llorracc/cstwMPC) up to the new [REMARK requirements](https://github.com/econ-ark/REMARK) because (a) I need to refactor the code a bit, but (b) I'm not sure how to go about that on code that is meant to be a reproducible research result. I expect that if cstwMPC is continued to be use as the basis of further research and pedagogy, then it will continue to be under pressure to change its shape as parts of it get reused.

One solution to this would be to [tag](https://developer.github.com/v3/git/tags/) the cstwMPC remark in a state where it reproduces the results, and then do whatever changes are necessary downstream in version control.

But I think this gets away from the spirit of things a bit. If there's some aspect of cstwMPC that is reusable in future research, then why wouldn't it be ported into a library?

Looking at the cstwMPC code now in HARK:
https://github.com/econ-ark/HARK/blob/254a77a51f23f21896943114155abf3833d6c1ca/HARK/cstwMPC/cstwMPC.py

I wonder whether any of this functionality is general enough that it could be broken out into more abstract HARK functionality, reducing the amount of code needed for the specific model.

For example, maybe the KYDifference based parameter estimation can be separated from the definition of the Dropout, High School, and College AgentTypes. Splitting out what's model specific configuration and what is more general functionality would make it easier to build on the original work. It would also disentangle the code in a way that would make the repository organization easier.

**Comment by llorracc** [comment]
Seb,

I agree that there are components to cstwMPC that could  be made into more general purpose tools to be incorporated in the main toolkit.  I'm working on some other things right now but let's get back to a discussion of this soon.

**Comment by MridulS** [comment]
ConsumptionSaving stays in, everything already moved out to examples/ or DemARK or REMARK.
