### ISSUE TITLE
break up requirements into user requirements and developer requirements to remove bloat

### ISSUE THREAD

**Issue by MridulS** [econ-ark/HARK#423]
Currently if someone installs HARK they will end up installing all the dependencies required for building documentation too, which unnecessarily adds bloat to the hark installation.
We can break up into absolute requirements like NumPy, SciPy, etc. and others as developer requirements.
`pip install Econ-ark` will work as usual but won't install documentation related dependencies, `pip install econ-ark[dev]` will install all the dependencies.

**Comment by llorracc** [comment]
Good idea.

A related issue.  I discovered a while ago that if you git clone a repo that contains submodules, the submodules are NOT cloned, they are empty.  Am guessing that you have to explicitly issue a git submodule update command of some kind inside your cloned repo before they will populate locally.  

My question is with how this fact affects the -dev version (which should include DemARK and REMARK as submodules).  As I understand things, this means that a git-cloned version of HARK will not retrieve the DemARK and REMARK content in place -- and therefore that the Sphinx documentation will not run properly locally?  Nor will Travis?  I'm asking because I was wishing a couple of days ago that I could both Travis and the ReadTheDocs documentation generation, in order to locally debug some things I was working on before making a pull request.  

PS.  Presumably we can do something to ensure that the pip install version does fetch whatever submodules we want it to get?

**Comment by sbenthall** [comment]
> We can break up into absolute requirements like NumPy, SciPy, etc. and others as developer requirements.

`https://packaging.python.org/discussions/install-requires-vs-requirements/` to do this:
 - put absolute dependencies in `setup.py` `install_requires`
 - put development dependencies in `requirements.txt`

Then instruct developers to run `pip install -r requirements.txt` to set up their environment.

@MridulS does this sound sufficient? I was trying to find the pattern for the `pip install econ-ark[dev]` pattern you opened with but couldn't find it.

**Comment by MridulS** [comment]
extra_requires in setup.py will work with that pattern.

**Comment by llorracc** [comment]
This sounds like a good idea
