### ISSUE TITLE
simplify code around time-varying solveOnePeriod methods

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#496]
Related to #492. There is some complexity introduced to handle the case where a solution algorithm depends on a `solveOnePeriod` function that varies over time. This involves putting it in the `time_vary` list of strings.

https://github.com/econ-ark/HARK/blob/master/HARK/core.py#L174-L176
https://github.com/econ-ark/HARK/blob/master/HARK/core.py#L896-L898

I have not been able to find a downstream case where this feature is used.

It is also a needlessly cumbersome way to signal that there are varying solution algorithms: since the code expects that `agent.solveOnePeriod` is indexical by `t`, a type check would suffice here. A boolean argument would also do, etc.

Other uses of the `time_vary` list seem to indicate things like state variables within the underlying MDP model. It is a rather confusing extension of scope to have this list contain both model variables as well as referenes to solution functions. Ideally, a well-defined model could be solved using more than one algorith.

I would like to simplify this aspect of the code.

Is this functionality needed? I.e. can it be removed entirely?
Otherwise, I can simplify it while leaving the functionality intact.

**Comment by mnwhite** [comment]
It's not "needed", in the sense that nothing is "needed".  I wrote this
feature very intentionally so that HARK could handle models where the
nature of the agent's problem changes over the course of his life.  Or
models where a "HARK period" actually corresponds to a subperiod of the
problem, and the agent's model can be characterized by repeatedly
encountering subperiod A, then subperiod B.  We don't currently have any
examples of this, but it's there intentionally to allow a lot more
flexibility in the kind of models that can be specified in HARK.

I don't think it's "needlessly cumbersome" to do it this way, but I'm open
to changing it.

**Comment by sbenthall** [comment]
That's interesting.
I'm not familiar with any sort of theoretical model like that.
Do you have an example from the literature in mind?

My first reaction to that is that if there were indeed periods of type A and B, the model could track which kind of period it was at each time step with a state variable, and then if there were two different ways of solving the problem, the (single) solution function could check that state variable before determining which one to run.
