### ISSUE TITLE
constructLognormalIncomeProcessUnemployment(parameters) is not a method?

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#538]
`constructLognormalIncomeProcessUnemployment(parameters)` is a fucntion defined in the ConsIndShockModel module.

It is called from within the AgentType with `constructLognormalIncomeProcessUnemployment(self)`--as if it's a method.

But it's not structured as a method. It's a standalone function.

This is one example of several other cases where something that is used much like a method is defined as a standalone function instead.

This is odd design.

**Comment by llorracc** [comment]
If it matters, it is quite specific to the particular case of the IndShockConsumerType and does not necessarily apply to superclasses that might inherit from it.

**Comment by mnwhite** [comment]
*Subclasses ^^

Yes, this is something that's existed since literally the first week of
HARK, but shouldn't be there.  It's a vestige of a previous design
structure, and we never fixed it.  This is the same reason that discrete
distributions are nested lists with a particular structure, rather than a
DiscreteDistribution class that has various capabilities.  We started out
very early on with a classless structure, and these are two bad vestiges of
that.

**Comment by sbenthall** [comment]
Cool. Thanks for confirming.

Seems like now is a good time to pay down the [technical debt](https://en.wikipedia.org/wiki/Technical_debt)--kind of funny, for a library about consumption, borrowing, etc.

Honestly, I'm very happy doing this kind of work.
It's the best way for me to get clarity on how things work, in terms of the modeling substance, and I think it's going to serve the project well in the long run.
