### ISSUE TITLE
move Documentation/notebooks to /examples as appropriate

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#558]
The notebooks in Documentation/notebooks should be moved into examples/ as appropriate.
Can do some cleanup in the process.

https://github.com/econ-ark/HARK/tree/master/Documentation/notebooks

**Comment by llorracc** [comment]
(continuing an email thread between @MridulS and @sbenthall and @llorracc, so there will be a record on GitHub):

The discussion on problems compiling from jupyter to sphinx made me realize a complication in the scheme to make DemARKs entirely self-contained so they can be emailed etc:  We rely extensively on the `latex_envs` notebook extension so that we can use standardized LaTeX commands for objects we use all the time (with the considerable advantage that these objects have exactly the same names in the code).  Like `DiscFac` is defined as `\beta'.

But if someone emails the document without the latexdefs.tex file, it won't compile properly.

The only way I can see around this problem is to add a tool to HARK.utilities that gets invoked at the beginning of every notebook and does what latexdefs.tex does.

**Comment by sbenthall** [comment]
In my opinion:
1. Executed jupyter notebooks can be emailed easily, like a document. These shouldn't be executed, they should be 'read-only'
2. If you want to execute a notebook, you'll need to do it in an environment equipped to do so.
3. The functionality where:
    - A emails notebook to B
    - B executes notebook locally with no environment setup or errors

is well beyond the scope of what can be done with a few lines of support code in a library whose purpose is something else.
If this functionality is important, it would be best to escalate it to the Jupyter notebook community.

**Comment by llorracc** [comment]
The functionality where:
A emails notebook to B
B executes notebook locally with no environment setup or errors

That's not what I had in mind.  What I had in mind was that the person has a proper installation of the econ-ark toolkit on their computer.  (Or they are running in an approved Docker container or VM).  

I could be persuaded that the goal of having DemARK notebooks be standalone has costs that are too great.  But so far, aside perhaps from the whole set of LaTeX nightmares, the costs to get from where we are to that goal do not seem large.  And, for LaTeX, maybe we should just insist that DemARK's should use the "least common denominator" LaTeX (defined by "does it work with reproduce.py").

**Comment by llorracc** [comment]
Hmmm, I didn't mean to close this.  Finger must have slipped.

**Comment by sbenthall** [comment]
I think this issue can be closed, as these Documentation/notebooks are now in examples/
