### ISSUE TITLE
always adding 'solution' to timeVary?

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#573]
In this line in `solve()`, the recently formed solution is added to the time varying parameter list.

https://github.com/econ-ark/HARK/blob/master/HARK/core.py#L386

I may be mistaken here, but I think that in an infinite horizon model, it should not be time-varying.
Is that right?

**Comment by mnwhite** [comment]
No, it should be in time_vary no matter what.  An infinite horizon problem
might have more than one period, so solution will be a list with more than
one element.  When timeFlip() is executed, we want that list to be
reversed().

After you remove all the timeFlip stuff, then there's no point in solution
being named in time_vary.  It's not used as a solver input, and time will
never be reversed for an AgentType.

**Comment by sbenthall** [comment]
Is `time_vary` used for anything besides the timeFlip stuff?

**Comment by mnwhite** [comment]
Yes.  solve() and the functions it calls need to know whether a particular
argument for solveOnePeriod is time-varying or time-invariant, and thus
whether to pass the entire attribute as the argument or just grab one
particular index from the list.

It can't just look at whether each element is a list, because sometimes the
value for one particular period *is* a list.

**Comment by sbenthall** [comment]
Ok. If I understand correctly, 'time_vary' is involved only with the solution logic.

It is not part of the simulation logic.

Is that correct?

**Comment by mnwhite** [comment]
That's correct, as far as I know.

**Comment by sbenthall** [comment]
Ok, this ticket is now fixed in a commit in PR #570 , which is ready for your review.
