### ISSUE TITLE
update() redundant with preSolve() in some cases ?

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#578]
On `IndShockConsumerType` calls `update()` at the end of its initializer

https://github.com/econ-ark/HARK/blob/3d3dbfea9f2192213ece38ca6912ed249336e392/HARK/ConsumptionSaving/ConsIndShockModel.py#L2035

`update` updates the IncomeProcesses, the AssetsGrid, and the SolutionTerminal
https://github.com/econ-ark/HARK/blob/3d3dbfea9f2192213ece38ca6912ed249336e392/HARK/ConsumptionSaving/ConsIndShockModel.py#L2077

`preSolve` then calls update SolutionTerminal again. Maybe it also used to update the IncomeProcess
https://github.com/econ-ark/HARK/blob/3d3dbfea9f2192213ece38ca6912ed249336e392/HARK/ConsumptionSaving/ConsIndShockModel.py#L2260

It looks like in most cases, the terminal solution is fixed by the model code, and does not change. So it may not require all the 'updating'--it needs to be available for the solver though.

**Comment by mnwhite** [comment]
updateSolutionTerminal() needs to be called in preSolve() because self.CRRA
might have changed since the object was created.  IndShockConsumerType
really should just called update() in its preSolve method, as most of our
other classes do.  There's an old, boring reason why it doesn't.  The main
reason it *should* be called is that many users (read: Chris' students) do
something like

`ThisType.PermShkStd = [1.10]`
`ThisType.solve()`

and expect that permanent shock standard deviation has changed for the
solver... but it hasn't.  They would need to call updateIncomeProcess()
before solving in order for IncomeDstn to be updated.

**Comment by llorracc** [comment]
My students are a good proxy for newcomers to the toolkit, I think, so ideally we should somehow try to head people off from making the mistakes that my students repeatedly make.

For the income shock distributions, somewhere I proposed that when the discretization of the distribution is constructed, the resulting object should contain all of the information needed to reconstruct the discretization, and not just be an array of numbers.  

I believe that someone mentioned that there is a mechanism whereby it is possible to set things up to trigger an action whenever the value of an object is changed.  I'd propose that we should set things up so that the last step of the .update() method is to set some boolean like DiscretizedWithCurrentParameters to true, and then when any parameter is touched that would change the discretization, a consequence of that would be to reset DiscretizedWithCurrentParameters to false.  Then the first thing that would happen when .solve() is first invoked it a test of whether DiscretizedWithCurrentParameters is true.  If not, then the .update() method could be invoked (and a warning message printed admonishing the user that the right way to do things is to .update() after you change parameter values.  

Actually, this whole logic might be extended to other aspects of the API's functioning as well.  So that, for example, there might be a `SolvedWithCurrentParameters` boolean that would get set to True when .solve() is run, but resetting, say, the CRRA parameter would trigger a change in its value to False.  Then when someone tried to use an object for which the flag was false, a warning message could be printed admonishing the user that the object is being evaluated with different parameter values than those that it was solved with.

**Comment by sbenthall** [comment]
> They would need to call updateIncomeProcess()
before solving in order for IncomeDstn to be updated.

Why not put `updateIncomeProcess()` into preSolve()

Or, remove `update()` altogether and put its functionality into preSovle().
I expect these operations are not so burdensome?

> For the income shock distributions, somewhere I proposed that when the discretization of the distribution is constructed, the resulting object should contain all of the information needed to reconstruct the discretization, and not just be an array of numbers.

This is connected to issue #519

**Comment by mnwhite** [comment]
Please don't remove update().  I strongly prefer to have a single method
that updates all constructed attributes from primitive parameters.  And
this shouldn't simply be preSolve because we want to move in the direction
of thinking about non-optimal policy functions (rules of thumb or
heuristics), so calling preSolve() to create attributes needed for
simulation seems weird.

As for why updateIncomeProcess isn't in update(), see my previous post:
there's an old, boring reason.  We can put it in update now, and I can make
a two line fix (for speed) elsewhere.
