### ISSUE TITLE
ConsumptionSavingModel will not load from outside sources

### ISSUE THREAD

**Issue by ganong123** [econ-ark/HARK#58]
Here are two places where it fails.
```
  File "/Users/ganong/repo/HARK/cstwMPC/cstwMPC.py", line 19, in <module>
    import ConsumptionSavingModel as Model

ImportError: No module named ConsumptionSavingModel
```

```
  File "/Users/ganong/repo/HARK/TractableBufferStock/TBSexamples.py", line 13, in <module>
    from ConsumptionSavingModel import ConsumerType, solveConsumptionSavingMarkov

ImportError: No module named ConsumptionSavingModel
```

However, when I run ConsumptionSavingModel.py directly, it runs with no trouble at all.

**Comment by ganong123** [comment]
Let me know if there's anything else I can do to help with reproducibility. Here's some platform information.

```
Version      : 2.7.11
Version tuple: ('2', '7', '11')
Compiler     : GCC 4.2.1 (Apple Inc. build 5577)
Build        : ('default', 'Dec  6 2015 18:57:58')
```

**Comment by mnwhite** [comment]
For reproducibility, let's try this:

1) Download and unpack a fresh copy of the repo; right now, the comments-and-cleanup branch has the most up-to-date code.
2) Open .../HARK/cstwMPC/cstwMPC.py in Spyder
3) Click the green arrow "run" button in the toolbar.

That should run a really small estimation ("beta-point infinite horizon") and tell you that beta=0.9893 or so.  You can also try doing this for .../HARK/ConsumptionSavingModel/TractableBufferStockModel.py ... That will take ~1 second and solve the same simple model two different ways.

If the method you used to run the modules and get that error is substantially different than the procedure I described, please tell me what you were doing.  If there are other ways to run files that should work but don't work, we want to know.

**Comment by JohnYeabinMoon** [comment]
ganong123,
The problem could be your python path. I guess that you ran cstwMPC.py in the cstwMPC folder.
In this case, ConsumptionSavingModel could not be called because the compiler did not know where ConsumptionSavingModel is, unless you inserted the path. 
Inserting the path is easy. You can see the command line sys.path.insert(0,'../') in cstwMPC.py
Check your Hark-cloned directory. In my case, I write:
sys.path.insert(0,'/Users/yeabinmoon/Documents/HARK-master/ConsumptionSavingModel')

**Comment by mnwhite** [comment]
John:

Without making that change, do you get the same error?  The lines

sys.path.insert(0,'../')
sys.path.insert(0,'../ConsumptionSavingModel')

are meant to work on every machine, no matter where you put HARK, because it's a relative filepath.  The intention is that it adds the directory directly above the current one (which should be the root directory of HARK), and the ConsumptionSavingModel directory off of that one.

**Comment by JohnYeabinMoon** [comment]
My understanding on python is not quite good to be honest. But,
Using just command 
import sys 
sys.path.insert(0,'../')
sys.path.insert(0,'../ConsumptionSavingModel')
did not import ConsumptionSavingModel.py. In fact, I had the same problem before. So I added the direct path, and it worked. I am using Jupyter by the way.

**Comment by mnwhite** [comment]
I have a guess of the problem.  Do:

import os
os.getcwd()

That should tell you the current working directory.  Before you run a file, the current working directory should be the one that the module is in.  You can change the CWD with os.chdir.  If you use Spyder and click the green arrow "run" button, it does a version of this by using the runfile command with the wdir keyword.

We strongly recommend using Spyder, an iPython IDE that comes with Anaconda.  Just type spyder at a command prompt after installing Anaconda.

**Comment by ganong123** [comment]
(1) I was (and continue to be) working in Spyder
(2) cstwMPC.py already had the snippet
```
import sys 
sys.path.insert(0,'../')
sys.path.insert(0,'../ConsumptionSavingModel')
```
But this was not sufficient to load the relevant functions.

In any case, switching to comments-and-cleanup branch in my fork resolved the issue. Thanks everyone for your help and I'll continue to report out issues as I find them.
