### ISSUE TITLE
overwrite current init_lifecycle with parameters from SolvingMIcroDSOPs

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#586]
@mnwhite writes:

> The lifecycle parameters in the SolvingMicroDSOPs parameter file should be moved into ConsIndShockModel.py as another example dictionary. It should probably overwrite the current init_lifecycle, which just has made up parameters to show how to do finite horizon.

**Comment by llorracc** [comment]
Something that has been on my to-do list forever is to revamp the baseline life cycle parameters.  There are various ways in which they are badly out of date in ways that likely have substantive consequences.

Possibly the most important of these is to incorporate the age-varying profile of transitory and permanent shock variances that Mridul transcribed from the Sabelhaus and Song paper and that is one of the options in the Portfolio blog post config file.  

@MridulS, can you work with @sbenthall on this?  In the end I decided not to use this for the portfolio blog post because it did not make a dramatic difference to the risky share results.  If these numbers were in the ConsIndShockModel lifecycle calibration, we could remove them entirely from the Portfolio blog post.
