### ISSUE TITLE
exact_match in drawDiscrete can be better supported

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#614]
The `drawDiscrete` method has an optional boolean argument `exact_match = False`, which appears to be designed to draw from a distribution such that the points will always be drawn such that their frequency will be as close as possible to their expected value.

https://github.com/econ-ark/HARK/blob/8edcebf067ebd1913f13f79c2b1bbd221f980f1b/HARK/simulation.py#L264-L276

This is a somewhat strange operation.

There is only one instance in the code where this argument is set to True. It is here, and I believe it is a mistake:

https://github.com/econ-ark/HARK/blob/master/HARK/ConsumptionSaving/ConsAggShockModel.py#L479

I wonder if this functionality can be removed.

**Comment by mnwhite** [comment]
It's not a mistake, and please don't remove it.  Chris prefers that all
discrete draws work like this, and there are reasons to use it.  It's a way
to "fake" the law of large numbers with a much smaller sample, so that
idiosyncratic shocks don't aggregate to generate what *looks like* an
aggregate shock.

**Comment by sbenthall** [comment]
Ok. It is only used once, and inconsistently, in the code base.

The place where it is used, it is hard-coded into one part of a model class and not otherwise documented.

If this is truly a feature, it should probably be better documented at in the more user-facing classes.

**Comment by llorracc** [comment]
Yes, it's quite a valuable trick, and should be preserved.  Actually, should be used more widely.  But certainly should be documented.  

Probably somewhere in the literature someone has proved that it's OK to do this, but it couldn't be hard to prove it asymptotically:  It's hard to see any reason it could hurt to impose on your data restrictions 
1. Are approximately true in small samples and become exactly true as the sample size approaches infinity
2. Produce a set of draws that would, themselves, be equally likely to have appeared as the actual draws that did appear

It would be good to add a comment in the code soliciting anyone reading it to provide a reference to any relevant literature they might know about.   Actually, that's an idea that we should implement generally: Whenever we do something that is not a completely standard and familiar operation, we could have a tag in the code asking any reader for any references they might find.  In fact, probably the way to do this would be to add a section to the "Contributor's Guide" about exactly what we'd like (ideally, a link to a doi), and a bibtex entry.  Then the code could just contain a link to that section of the contributor's guide explaining what we want.  I guess another part of the workflow would be to make an "Issue" in the issue tracker and mark it as something an outsider could help with.

@sbenthall, can you make an Issue of this?

**Comment by mnwhite** [comment]
Code comments that ask questions is a bit non-standard, I think.

Forcing a simulated population to have the exact distribution of
discretized shocks is a good idea *if and only if* the person running the
code know that's what's happening.  It also only works exactly if the
discrete probabilities are rational numbers, which isn't necessarily the
case.

Simulating on discretized shocks also reduces the variance of shocks
actually experienced, which might be an undesirable property.

**Comment by llorracc** [comment]
> Code comments that ask questions is a bit non-standard, I think. 

That's OK with me.  It is doing a favor to the user of the code to flag items where we have done something that perhaps should be thought about carefully in case there's some circumstance under which it might not be a good idea.

> Forcing a simulated population to have the exact distribution of discretized shocks is a good idea *if and only if* the person running the code know that's what's happening.

Right -- again this is a reason to flag this as something that could use some more backup/thinking.

> It also only works exactly if the discrete probabilities are rational numbers, which isn't necessarily the case. 

It definitely _not_ the case in the usual theory, in which we are discretizing a continuous distribution.  But I feel that this is well understood by everyone doing this kind of thing.

> Simulating on discretized shocks also reduces the variance of shocks actually experienced, which might be an undesirable property.

Well, it does so only because the sample is finite.  As the sample size approaches infinity, it has no effect.  And everybody is always trying to approximate an infinite population with a finite number of agents, so the reduction in variance is a feature not a bug (in that it causes the variance to be closer to what you would get if you could really do an infinite population).

**Comment by mnwhite** [comment]
Sorry, I should have been cleared on that last point.  I meant that
discretizing using your "partitioned inverse CDF" method and then drawing
from that (rather than the true continuous dstn) will reduce variance.  I
used bad shorthand.

**Comment by sbenthall** [comment]
> @sbenthall, can you make an Issue of this?

I don't really understand what you are asking me to do.
Maybe we should discuss it on a call.

**Comment by sbenthall** [comment]
functionalize out the `exact_match` functionality to support the equiprobable permutation use case for seeding the simulation with the ergodic distribution.

**Comment by sbenthall** [comment]
this is now a documented feature of DiscreteDistribution, which seems fine.
