### ISSUE TITLE
delay discretization of random parameters

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#640]
In conversation, @llorracc floated the idea that HARK, like Mathematica, could delay the discretization of random variables until it was necessary for sampling.

This seems doable with changes to the distribution representation. See #519 #611 

Based on the existing code, the main design question that raises is when the number of values in the discretized distribution is set. Currently, this is a parameter given to the model on initialization:

https://github.com/econ-ark/HARK/blob/master/HARK/ConsumptionSaving/ConsPrefShockModel.py#L24

**Comment by llorracc** [comment]
I feel that the object that contains the discretized results needs to store all the parameters that went into its creation.  One reason for this is that users often change parameter values without realizing that in order for those parameter values to actually apply they need to rediscretize (and also re-solve) the model.  If the parameters were stored, we could do a quick check of whether the current values match the ones that were in force at the time of discretization, and if not we could at least give a warning.  (We would NOT want to prohibit the use of a different discretization than the parameters currently specify, because that is something that occasionally someone might want to do deliberately).

**Comment by sbenthall** [comment]
Looking over the source code on this, it looks to me that there are two different code patterns used around instantiating random variables.

In some cases, the random variable object is constructed, left continuous, and immediately sampled. This happens in `simBirth`

https://github.com/econ-ark/HARK/blob/master/HARK/ConsumptionSaving/ConsIndShockModel.py#L1510-L1514

In this case there is no discretization, so this ticket does not apply.

In other cases, a distribution is approximated and stored. This is done partly because the distribution is a joint distribution (though in these cases it is an independent join distribution):

**Comment by sbenthall** [comment]
Today @llorracc says that the only reason to delay discretization is ... to assist in debugging of the non-discretized model.

**Comment by sbenthall** [comment]
Because there's no major motivation for delaying discretization of a random variable, I'll close this ticket.

I'll bring up the question of simulation in the continuous space in issue #660
