### ISSUE TITLE
several examples are broken

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#649]
Several examples are broken with recent changes.

I'll work through these and make automated tests as necessary.

I wonder how we can catch these better in an automated way.
Maybe run them with pytest as part of an automated PR test.

**Comment by MridulS** [comment]
> Maybe run them with pytest as part of an automated PR test.

If I remember correctly we discussed this before and it takes an extra 40 mins to run all the examples.

**Comment by llorracc** [comment]
I guess the "recent changes" were the ones this morning?

That reminds me:  We've discussed setting things up so that a more extensive battery of tests (the examples; maybe the `do_min` part of the REMARKs) runs nightly.  Where do we stand on that?

Seems like a fix might be for there to be somehow sort of `do_min` versions of the examples.  Maybe this could be handled by putting in a metadata tag on all the cells, like "runsFast" or "runsSlow" and then for the automated tests running only the "runsFast" cells?
