### ISSUE TITLE
HARK.utilities missing approxUniform?

### ISSUE THREAD

**Issue by merajindc** [econ-ark/HARK#687]
Hello, 

I'm new to HARK (kind of). I was going through some of the tutorials and noticed that I do not have approxUniform in my HARK.utilities 
or
when I import approxUniform from HARK.utilities, it cannot be found. 

I just installed HARK today from conda. I have other things in HARK.utilities like utility functions, but not this approximated uniform distribution. I'm on a windows machine, running ananconda

Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]

**Comment by MridulS** [comment]
`approxUniform` exists in HARK.distribution in the latest release v0.10.6.

```
from HARK.distribution import approxUniform
```

**Comment by sbenthall** [comment]
The way to approximate distributions has changed _since_ the v0.10.6 release. This breaks some of the materials that have been built on top of HARK.

@merajindc would you be able to tell us which tutorials gave you this error?

If you would like to approximate a Uniform distribution using the unreleased `master` branch (or in future version v0.10.7 or later), the code is:

`from HARK.distribution import Uniform`

`Uniform(bot=0, top=1).approx(10)`

for example.

**Comment by merajindc** [comment]
Sebastian,

I found this problem in /DemARK-master/notebooks/Chinese-Growth.ipynb

i changed it to HARK.distribution and it worked fine.

im just getting started in HARK, and will be entering the dissertation
planning phase with Rob Axtell this summer or fall. I'm a macro guy that
went back to get a phd. I've had conversations with Chris about this
project, but im getting up to speed on python first before i can commit to
helping out. I will likely be going through all of the DemARK notebooks so
i can keep a running list of bugs. Im not using git so i just downloaded
the zip file.

thanks,

Meraj

**Comment by sbenthall** [comment]
Ah, ok, thank you.

good luck on your dissertation planning. A dissertation that combines Econ-ARK with Robert Axtell's expertise would be fascinating. @llorracc and I have been discussing ways to synthesize Econ-ARK with Mesa, an ABM toolkit that was developed by some people that worked with Axtell.

I'll try to keep you in the loop if there's any progress on that front on our end.

I believe the DemARK issue you've raised is fixed in this PR, which hasn't yet been merged, but could be.
https://github.com/econ-ark/DemARK/pull/116

I'd encourage you to post problems you find with DemARKs on that issue tracker; this one is intended for the HARK library.

Also, while git/GitHub can be confusing, there's a lot of upside to learning them and I'd encourage you to take it up.
