### ISSUE TITLE
enable the ConsAggShockModel market test....

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#689]
... in a way that makes it run very fast.
 - crank up the economy.tolerance
 - reduce act_T to a very small number

precondition for #674

**Comment by mnwhite** [comment]
The other part of this I need to look into is the performance issues in ConsAggShockModel, particularly the Markov version.  The example that used to take ~4 minutes is now taking 25+ minutes, even when I turn down the number of simulated periods.

**Comment by sbenthall** [comment]
see also #567

**Comment by mnwhite** [comment]
As a first hint of what's changed / going wrong, the solve_agg_shocks_market example takes the same time to run in HARK 0.10.5 as it does now, while solve_krusell_smith (using the Markov aggregate shocks model) took 74 seconds in 0.10.5 but 83.5 seconds in the latest version.

The big thing is solve_markov_market, which took 252 seconds in 0.10.5 but 1571 seconds in the current version.  All that's changed is the new distribution classes, and the problem is in simulation: solve_markov_micro (no simulation) takes ~17 seconds in both versions.

**Comment by mnwhite** [comment]
The speed issue is resolved by #702

**Comment by mnwhite** [comment]
I think this has been resolved?

**Comment by sbenthall** [comment]
I agree.
