### ISSUE TITLE
checkConditions runs automatically and prints output to screen

### ISSUE THREAD

**Issue by mnwhite** [econ-ark/HARK#699]
Solving an IndShockConsumerType automatically prints output to screen.  This is absolutely not what we want to happen.

**Comment by sbenthall** [comment]
I believe this is connected to #283 
At the end of that issue is a proposal for a new design for logging that has passed @llorracc 's review.

**Comment by mnwhite** [comment]
Whoops, I forgot we had already discussed this.

**Comment by sbenthall** [comment]
it's all good. Thanks for reminding me I need to fix it

**Comment by sbenthall** [comment]
@mnwhite I think you and @llorracc may have a design disagreement here?

https://github.com/econ-ark/HARK/issues/283#issuecomment-600279552

I think that @llorracc wants checkConditions to normally print _some_, but not all, of the messages when IndShockConsumerType is solved(). He has asked that the "quiet" option be something that can be set for individual notebooks.

If I understand you correctly, I think you are saying here that you think that turning on the print statements for checkConditions should be opt in.

From my perspective, this is a matter of deciding which of three proposed logging settings (normal, "verbose", or "quiet") is the default. I have no opinion on this.

I'll get the flexible logging framework described in #283 in as a PR and let you and @llorracc hash out the details here, since it seems to be mainly a question of how best to address the tensions between pedagogical and research use cases.

**Comment by mnwhite** [comment]
This was fixed long ago, closing.
