### ISSUE TITLE
Add setup.py so module can be installed.

### ISSUE THREAD

**Issue by theoldfather** [econ-ark/HARK#85]

**Comment by mnwhite** [comment]
This has been discussed and an early version was developed.  I believe we decided to hold off on this for a while, but now I forget our reasoning.  Leaving open for others to fill in details.

**Comment by brainwane** [comment]
I'm working on this in https://github.com/brainwane/HARK/tree/installability which I should have linked here much earlier - apologies! I should have it merged into `master` later today.

**Comment by brainwane** [comment]
We have some early developer releases available for `pip install` at http://pypi.org/project/econ-ark and `conda install` at https://anaconda.org/sumanah-changeset/econ-ark .

**Comment by mnwhite** [comment]
Before merging the installability branch into master, can we fix the Models vs Demos issue?

**Comment by brainwane** [comment]
Thank you for that very good point, @mnwhite!

The Models versus Demos issue @mnwhite mentioned is: in the `installability` branch, we've changed the structure of the code, with several commits by @jasonaowen -- some of which he'd like to do over, reverting how he separated out Demos.

@compumetrika asked when we were planning on merging the `installability` branch back into `master`, and I originally suggested doing it this week. But @mnwhite makes a good point: it would be nice to have only one giant breaking change in `master` instead of two in a row. We do have some time pressure here, since we want to get this all merged and tested, and cut a new release, before Tuesday, 19 June (when Chris and Matt do their next public demo).

So here's how I propose to do this:

* Today, I'll make a separate pull request with other cleanup that's immediately applicable to the `master` branch.
* Tomorrow, I'll further prepare `installability` to make it more ready to merge into `master`.
* Next week, starting Monday, Jason will address the Models vs Demos issue on `installability`.
* After he's done that, ideally in the middle of next week, we make a pull request to merge `installability` into `master`, and get that reviewed and merged.

**Comment by mnwhite** [comment]
(Non-code note: I'm back stateside.  Chris is doing the Bank of England and Venice presentations solo!)
