### ISSUE TITLE
makeEulerErrorFunc never used

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#892]
`makeEulerErrorFunc` is defined for many models, but never called or tested.

https://github.com/econ-ark/HARK/search?q=makeEulerErrorFunc&type=code

Should this code be removed?

Alternatively, can it be rewritten more simply using `calcExpectations`? See #625

**Comment by mnwhite** [comment]
I can be rewritten with calcExpectations, but I don't think it should be
deleted.  It has a trivial `notImplementedError` definition in many models
because those classes inherit from IndShockConsumerType, the only class
it's properly defined for.  Maybe it's in KinkedRType as well? The base
definition in ConsIndShockModel would be incorrect for any other model.

This is one of those features that could eventually have a "magic" version
once everything is equation-ified.

**Comment by sbenthall** [comment]
I see now that it contains redundant information with the solution code.

I'm trying to figure out how to consolidate the solution code use calcExpectations. See #893 

I would rather rewrite the solution code to use a well-contained euler function than remove the well-contained euler function. But I think the redundant information should be removed.

I think we are closer to a 'magic' version than you might think, but the first step is to tighten what's already there.

**Comment by sbenthall** [comment]
Add a note in the documentation explaining why this method is here.
Suggesting that it's used for testing and benchmarking other implementations of the solver or model...
