### ISSUE TITLE
Should solvers have access to Agent.conditions?

### ISSUE THREAD

**Issue by Mv77** [econ-ark/HARK#924]
Currently, in `ConsIndShockModel.py`, `checkConditions()` checks for different patience conditions and stores the results in `conditions`, which is a property of the Agent.

The solution of the models in that file takes place in `solvers`, which are objects different from agents (each agent has a `solveOnePeriod` method that comes from a solver object). This, I believe, makes it so that a solver cannot access the `conditions` of the agent it is "solving".

I wanted to open a discussion of whether solvers should have access to `conditions`, since for instance:
- #899 puts the methods to find the stable points of a solution inside the solver, and their existence depends on whether, e.g, the GIC is satisfied. This results in the solver having to check the GIC when it might have been computed already by the Agent object.
-  I presume there are models in which the information of which conditions are met is useful for e.g. speeding up the solution or deciding which method to use.

**Comment by llorracc** [comment]
I guess the question is really whether the solver, or solveOnePeriod, should have access to all of the precomputed characteristics of the agent whose problem it is trying to solve automatically.  

If there were no cost to this, it would be a no-brainer: Yes.  Then, as @Mv77 points out, solution techniques could (for example) be tailored to the known characteristics that the solution will satisfy (e.g., a target exists).   

What I don't have the expertise to judge is whether making the rich set of data already computed for the agent, or some subset of that data, available to the solver would be difficult or easy, and whether it would be computationally costly (in memory or time) or computationally cheap.  If cheap in both respects, I say we adopt Mateo's proposal as a to-do.

**Comment by mnwhite** [comment]
The `conditions` dictionary is only produced for infinite horizon models with a single repeated period; otherwise this step is skipped. I also moved computation of target mNrm values *outside* the solver, to be computed after the solution is constructed, because they were such a massive slowdown on the solver (and not useful in many cases).

It's extremely easy to provide additional information to a solver. In our discussions, we've talked about using traits like value function concavity to choose among solution methods. In the framework we're moving toward, the various theoretical conditions *can't* have any meaning within a one period solver, because that solver has no knowledge of other periods, and those conditions depend on the structure of the entire problem.
