### ISSUE TITLE
Make sure examples/ are all working

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#943]
I believe that making sure examples/ are working is part of our release cycle for HARK, but it's not currently part of the automated test regimen.

At the time of this writing, it looks like not all of the examples/ are functioning.

It is _especially_ important to have them all working for the 1.0 release.

**Comment by sbenthall** [comment]
reassigning to Mridul because you seem to be working on it with #944 ?

**Comment by MridulS** [comment]
for reference, broken examples (mostly because of `Now`)
- examples/ConsIndShockModel/IndShockConsumerType.py
- examples/ConsIndShockModel/PerfForesightConsumerType.py
- examples/ConsumptionSaving/example_ConsMedModel.py
- examples/ConsumptionSaving/example_TractableBufferStockModel.py
- examples/ConsumptionSaving/example_ConsPortfolioModel.py
- examples/ConsumptionSaving/example_ConsMarkovModel.py
- examples/ConsumptionSaving/example_ConsRepAgentModel.py
- examples/ConsumptionSaving/example_ConsGenIncProcessModel.py
- examples/ConsumptionSaving/example_ConsPrefShockModel.py
- examples/FashionVictim/FashionVictimModel.py
- examples/GenIncProcessModel/GenIncProcessModel.py
- examples/HowWeSolveIndShockConsumerType/HowWeSolveIndShockConsumerType.py
-

**Comment by sbenthall** [comment]
I'm confused why we are support these .py examples. Most of our examples are notebooks. For some reason, these .py files are not Jupyter linked with the corresponding notebooks? Why are we maintaining them like this?
