### ISSUE TITLE
lifecycle ConsPortfolioModel example broken by new lifecycle calibration?

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#975]
The ConsPortfolioModel contains a lifecycle example. This example is currently breaking because the time varying lists of `RiskyAvg` and `RiskyStd` are of length 10, and `T_cycle` is of length 65. I believe this change is due to the recent Calibration updates from @Mv77 

https://github.com/econ-ark/HARK/blob/master/examples/ConsumptionSaving/example_ConsPortfolioModel.ipynb

I'll disable the lfiecycle example in the notebook for the 1.0 release so tests pass.
But a high priority for a 1.0.1 release should be:
 - fixing this example
 - adding automated test for this use case so it doesn't happen again.

**Comment by llorracc** [comment]
@Mv77 @sbenthall,

Actually, this is practically the only case in which the old calibration that we used to call a "life cycle" calibration was at all appropriate.  It was a "life cycle" only in being a finite interval of time, not in having any sensible pattern over the lifetime.  If whatever was in the old life cycle calibration can be resurrected and just stuck into this example by _force majeure_, the example will work again and that will be a perfectly good solution.  @Mv77, since you replaced the life cycle calibration, am guessing it would take you very little time to dredge up the old calibration and stick it in here by hand?

**Comment by Mv77** [comment]
Fixed (and merged) in #977.

It did not add a test. I do not know where tests for examples are and how they are to be structured given that in the patch I saw the `.py`'s are being removed.

**Comment by Mv77** [comment]
*It was merged into "MridulS-Patch1", not master because that's where the commit pointed to.
