### ISSUE TITLE
Is t_age a state?

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#983]
I'm working on updating the old cstwMPC code and it does something that's for me unexpected.
It tries to pull in the agent's `t_age` data into the Market class as a `reap_var`.

We've been separating out different kinds of 'model variables' -- states, controls, shocks -- into separate namespaces.

But variables like `t_age` and `t_cycle`, which are more about the 'population model' than the structural equations model defined under the SDP framework, have remained part of the core machinery without this treatment.

I can hack around this for the cstwMPC update, but I think it raises an interesting question about how to deal with `t_age` moving forward.

See related tickets: #95 #669 #837 #847

**Comment by mnwhite** [comment]
This is sort of a philosophical question. In the "taxonomy of variables"
that I preach, the mathematical objects that t_age and t_cycle represent
are not "state variables", but rather "time variables". However, "time
variables" can be considered a special class of "state variable" because of
their trivial dynamics: a time variable is a state variable that evolves
monotonically and with no uncertainty. We could write $age' = age + 1$ and
define age to be (mathematically) part of the individual's state, but in
the Bellman phrasing of problems we use the convenient fact that things
happen one after another to break down an intertemporal problem into a
sequence of feasible steps.

In a continuous time model (not our bag) that includes age, it's just
another state variable with trivial dynamics: agents move through the age
dimension at a constant positive rate.

For cstwMPC, I think I reap t_age because a bunch of the internal
statistics collecting and computing is done at the market level. It's
gathering that data for application purposes, not model purposes. However,
it's entirely possible to write a model where market outcomes actually do
depend on the distribution of ages.

**Comment by mnwhite** [comment]
Closing this issue for being stale and not really something to resolve. HARK 1.0 will have a different age-tracking structure anyway.
