### ISSUE TITLE
EmpNow in IndShockConsumerType ?

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#984]
It looks like there is some residual use of `EmpNow` in IndShockConsumerType even though it is not recorded as a shock.

https://github.com/econ-ark/HARK/blob/05ef324cfc7b0351b68063ce3cbcc70a47f62783/HARK/ConsumptionSaving/ConsIndShockModel.py#L2161-L2163

It looks like the cstwMPC code assume that this is there, and is available for inspection.

Is this part of the model, or not?
Can it be removed?

I can hack around it in the cstwMPC refactor

**Comment by llorracc** [comment]
“Unemployment” in the model is just captured by a special value of the transitory shock.  Like, if there were no unemployment insurance it would be zero.  In the paper we tabulate various facts for ‘unemployed’ people, so it is useful to create a Boolean to mark them.  If the main HARK ConsIndShock model code doesn’t do this probably it would be worth adding it there and just using it in cstw but I don’t feel strongly about it

**Comment by mnwhite** [comment]
Yes, that's how it's constructed in cstwMPC. It's not drawn as a shock
itself, but instead calculated as something like:

`self.EmpNow = self.TrankShkNow == self.IncUnemp`

Or whatever the correct phrasing is now with dictionaries. The
cstwMPC project wanted to calculate some statistics by employment state,
and this was the most straightforward way to do that.

**Comment by mnwhite** [comment]
Chris wants this functionality to remain in HARK, but it actually needs to *leave* and be moved to cstwMPC (and other applications that use it). Going forward, the simulation code for ConsIndShock can't be sure that IncUnemp *exists*-- it's an input to a constructor, not a fundamental part of the model that's required to exist. So these two lines need to be excised and put elsewhere (currently 2048-2049 of ConsIndShockModel):

`self.EmpNow = np.ones(self.AgentCount, dtype=bool)`
`self.EmpNow[TranShkNow == self.IncUnemp] = False`

**Comment by llorracc** [comment]
I strongly object to removing the unemployment shock, as a possibility, from the ConsIndShock model.  It is an extremely valuable tool for understanding the fundamental mechanics and math of the model.  The whole BufferStockTheory paper relies profoundly and intimately on this.

**Comment by mnwhite** [comment]
That's not what I'm saying-- unemployment is not being removed as an
option. It's still in HARK, it's still the default, and it will remain that
way.

All that I'm flagging for removal is 2 lines in the simulation code that
*assume* there is an attribute called `IncUnemp`, the level of the
transitory shock when "unemployed". That parameter *doesn't necessarily
exist* if someone doesn't use the default income process.

Those 2 lines are only in HARK because of cstwMPC-- an application of HARK.
I'm saying they should be removed from HARK itself (where they could cause
an error) and into the application where they're actually used.

      -- mnw

**Comment by Mv77** [comment]
@llorracc I'm with @mnwhite on this one.

This is not removing the ability of incorporating unemployment shocks at all. Nothing fundamental about the model and its flexibility changes.

There are just 2 annoyingly specific lines of accounting for a *particular* application (cstwMPC) that were added to this very general income process that almost every class in hark inherits. It is unreasonable to enforce that particular accounting mechanism on every model in HARK. This is, for instance, preventing me from updating my JMP to the latest HARK version.

As @mnwhite said elsewhere, since cstwMPC is an application, it should have created its own class inheriting from ConsIndShock and added whatever particular features it wanted on top of it instead of adding its particular flavor of kool-aid at the water source and forcing it on the whole town.

**Comment by llorracc** [comment]
OK.  At some  Point in the past, we had incorporated the unemployment shock
simply as the lowest value of the transitory shock distribution and I
interpreted what Matt wrote as being a desire to move back to that way of
doing things. Fine with the changes as you and Matt have more fully
described them.
